//! The 'abscs' theme collection in this module was extracted from <https://github.com/Abstract-IDE/Abstract-cs> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn abscs() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(255, 250, 222), Some(Color::new(6, 6, 6)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(233, 116, 81), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(237, 114, 46), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(1, 160, 245), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(80, 193, 110), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(157, 151, 151), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(92, 77, 77), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(255, 0, 0), None, false, false, false, false)),
        ("comment.hint".into(), Style::new(Color::new(251, 177, 60), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(255, 204, 102), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(255, 255, 255), Some(Color::new(59, 59, 29)), false, false, false, false)),
        ("comment.warning".into(), Style::new(Color::new(251, 177, 60), None, false, false, false, false)),
        ("conceal".into(), Style::new(Color::new(255, 250, 222), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(255, 204, 102), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(189, 51, 164), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(112, 41, 99), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(1, 160, 245), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(179, 246, 192), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(255, 255, 255), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(0, 191, 255), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(0, 107, 60), None, false, false, false, false)),
        ("function.method".into(), Style::new(Color::new(136, 119, 177), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(17, 17, 17), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(119, 119, 119), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(55, 60, 69), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(227, 0, 34), None, false, false, false, false)),
        ("keyword.exception".into(), Style::new(Color::new(214, 142, 178), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(1, 142, 213), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(249, 38, 114), None, false, false, false, false)),
        ("keyword.repeat".into(), Style::new(Color::new(227, 0, 34), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(252, 41, 41), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(136, 136, 136), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(237, 114, 46), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(255, 255, 153), None, false, false, false, false)),
        ("markup.italic".into(), Style::new(Color::new(204, 204, 204), None, false, false, true, false)),
        ("markup.link".into(), Style::new(Color::new(29, 145, 139), None, false, false, false, false)),
        ("markup.list".into(), Style::new(Color::new(252, 41, 41), None, false, false, false, false)),
        ("markup.quote".into(), Style::new(Color::new(187, 187, 187), None, false, false, false, false)),
        ("markup.strong".into(), Style::new(Color::new(228, 113, 122), None, false, false, false, true)),
        ("module".into(), Style::new(Color::new(255, 255, 255), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(237, 114, 46), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(255, 204, 102), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(214, 142, 178), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(249, 38, 114), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(0, 204, 153), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(204, 204, 204), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(163, 193, 173), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(193, 154, 107), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(120, 134, 107), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(207, 92, 54), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(255, 8, 0), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(255, 8, 0), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(157, 151, 151), None, false, false, false, false)),
        ("string.special.symbol".into(), Style::new(Color::new(89, 39, 32), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(179, 27, 27), None, true, false, false, false)),
        ("tag".into(), Style::new(Color::new(23, 140, 148), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(237, 114, 46), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(29, 145, 139), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(252, 41, 41), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(0, 191, 164), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(153, 186, 221), None, false, false, false, false)),
        ("variable.member".into(), Style::new(Color::new(5, 210, 221), None, false, false, false, false)),
        ("variable.parameter".into(), Style::new(Color::new(127, 190, 235), None, false, false, true, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(237, 114, 46), None, false, false, false, false)),
    ]))
}
