//! The 'aurora' theme collection in this module was extracted from <https://github.com/ray-x/aurora> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn aurora() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(221, 208, 244), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("annotation".into(), Style::new(Color::new(130, 170, 240), None, false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(255, 67, 91), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(255, 206, 81), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(249, 39, 114), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("comment".into(), Style::new(Color::new(97, 137, 187), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(238, 130, 238), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(251, 252, 191), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(231, 60, 80), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(249, 39, 114), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(102, 144, 196), None, false, false, false, false)),
        ("debug".into(), Style::new(Color::new(255, 99, 71), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("define".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("definition".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("definition.usage".into(), Style::new(Color::new(230, 219, 116), None, false, false, false, false)),
        ("emphasis".into(), Style::new(Color::new(251, 237, 125), None, false, false, true, false)),
        ("exception".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(158, 113, 207), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(249, 39, 114), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(102, 217, 239), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(15, 185, 224), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(190, 154, 247), None, false, false, false, false)),
        ("identifier".into(), Style::new(Color::new(218, 207, 228), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(213, 124, 213), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(196, 162, 255), None, false, false, true, false)),
        ("keyword.coroutine".into(), Style::new(Color::new(241, 155, 182), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(15, 185, 224), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(250, 177, 194), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(179, 118, 179), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(26, 173, 22), None, false, false, false, false)),
        ("literal".into(), Style::new(Color::new(218, 207, 228), None, false, false, false, false)),
        ("macro".into(), Style::new(Color::new(195, 60, 74), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("method".into(), Style::new(Color::new(16, 174, 248), None, false, false, false, false)),
        ("method.call".into(), Style::new(Color::new(102, 217, 239), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(231, 195, 251), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(253, 151, 32), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(161, 239, 228), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(251, 236, 159), None, false, false, false, false)),
        ("parameter.reference".into(), Style::new(Color::new(161, 239, 228), Some(Color::new(33, 28, 47)), false, false, false, true)),
        ("preproc".into(), Style::new(Color::new(238, 130, 238), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(158, 113, 207), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(255, 99, 71), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(122, 166, 218), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(231, 195, 251), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("punctuation.spectial".into(), Style::new(Color::new(231, 197, 71), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(255, 114, 115), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(1, 213, 241), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(26, 188, 156), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(161, 239, 228), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(241, 155, 182), None, false, false, false, false)),
        ("strong".into(), Style::new(Color::new(219, 192, 138), None, false, false, false, false)),
        ("structure".into(), Style::new(Color::new(161, 239, 228), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(173, 219, 103), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(161, 239, 228), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(255, 99, 71), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("text".into(), Style::new(Color::new(221, 208, 244), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("text.danger".into(), Style::new(Color::new(220, 20, 60), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("text.environment".into(), Style::new(Color::new(195, 60, 74), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(103, 213, 181), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(26, 188, 156), None, false, false, false, false)),
        ("text.math".into(), Style::new(Color::new(255, 99, 71), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("text.note".into(), Style::new(Color::new(255, 99, 71), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("text.reference".into(), Style::new(Color::new(251, 252, 191), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(108, 103, 234), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(0, 0, 255), Some(Color::new(255, 255, 0)), false, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(128, 160, 255), None, true, false, false, false)),
        ("text.warning".into(), Style::new(Color::new(236, 95, 103), None, false, false, false, false)),
        ("title".into(), Style::new(Color::new(236, 196, 141), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(103, 213, 181), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(255, 206, 81), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(102, 217, 239), Some(Color::new(33, 28, 47)), false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(103, 213, 181), None, false, false, false, false)),
        ("underline".into(), Style::new(Color::new(236, 196, 141), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(231, 195, 251), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(253, 151, 32), None, false, false, false, false)),
    ]))
}
