//! The 'boo' theme collection in this module was extracted from <https://github.com/rockerBOO/boo-colorscheme-nvim> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn boo() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(225, 217, 234), Some(Color::new(15, 15, 16)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(114, 84, 120), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(185, 158, 231), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(132, 157, 162), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(63, 52, 66), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(102, 145, 154), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(83, 117, 126), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(125, 108, 130), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(66, 145, 173), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(125, 108, 130), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("debug".into(), Style::new(Color::new(101, 74, 150), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(205, 116, 156), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(132, 157, 162), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(101, 74, 150), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(125, 162, 169), None, false, false, true, false)),
        ("function.builtin".into(), Style::new(Color::new(58, 114, 114), None, false, false, false, false)),
        ("function.call".into(), Style::new(Color::new(77, 162, 179), None, false, false, true, false)),
        ("function.macro".into(), Style::new(Color::new(125, 162, 169), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(101, 74, 150), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(104, 76, 154), None, false, false, true, false)),
        ("keyword.function".into(), Style::new(Color::new(104, 76, 154), None, false, false, true, false)),
        ("keyword.operator".into(), Style::new(Color::new(104, 76, 154), None, false, false, true, false)),
        ("keyword.return".into(), Style::new(Color::new(104, 76, 154), None, false, false, true, false)),
        ("label".into(), Style::new(Color::new(99, 176, 176), None, false, false, true, false)),
        ("macro".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(77, 162, 179), None, false, false, true, false)),
        ("method.call".into(), Style::new(Color::new(77, 162, 179), None, false, false, true, false)),
        ("namespace".into(), Style::new(Color::new(161, 180, 184), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(217, 214, 207), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(101, 101, 104), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(169, 209, 223), None, false, false, false, false)),
        ("parameter.reference".into(), Style::new(Color::new(169, 209, 223), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(132, 157, 162), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(143, 143, 183), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(101, 101, 104), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(97, 97, 108), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(115, 127, 141), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(83, 117, 126), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(218, 243, 243), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(218, 243, 243), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(218, 243, 243), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(218, 243, 243), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(133, 193, 193), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(115, 141, 141), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(59, 70, 73), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.emphassis".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.environment".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.math".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.reference".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.strike".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.string".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(63, 52, 66), None, false, false, false, false)),
        ("text.underline".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(72, 133, 133), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(116, 138, 144), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(148, 194, 210), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(59, 99, 146), None, false, false, false, false)),
    ]))
}
