//! The 'boo' theme collection in this module was extracted from <https://github.com/rockerBOO/boo-colorscheme-nvim> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn boo() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(225, 217, 234), Some(Color::new(15, 15, 16)), false, false, false, false)),
        ("annotation".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(114, 84, 120), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(101, 74, 150), None, false, false, false, false)),
        ("attribute.typescript".into(), Style::new(Color::new(97, 175, 239), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(185, 158, 231), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(63, 52, 66), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(92, 99, 112), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(201, 136, 223), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(232, 102, 113), None, false, false, true, false)),
        ("comment.todo.checked".into(), Style::new(Color::new(152, 195, 121), None, false, false, true, false)),
        ("comment.todo.unchecked".into(), Style::new(Color::new(232, 102, 113), None, false, false, true, false)),
        ("comment.warning".into(), Style::new(Color::new(192, 192, 221), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(83, 117, 126), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(125, 108, 130), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(66, 145, 173), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(125, 108, 130), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("danger".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, false)),
        ("diff.add".into(), Style::new(Color::new(152, 195, 121), None, false, false, false, false)),
        ("diff.delete".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(97, 175, 239), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(152, 195, 121), None, false, false, false, false)),
        ("error".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(86, 182, 194), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(125, 162, 169), None, false, false, true, false)),
        ("function.builtin".into(), Style::new(Color::new(58, 114, 114), None, false, false, false, false)),
        ("function.call".into(), Style::new(Color::new(77, 162, 179), None, false, false, true, false)),
        ("function.macro".into(), Style::new(Color::new(125, 162, 169), None, false, false, false, false)),
        ("function.method".into(), Style::new(Color::new(97, 175, 239), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(49, 53, 63), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(92, 99, 112), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(92, 99, 112), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(101, 74, 150), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(104, 76, 154), None, false, false, true, false)),
        ("keyword.conditional".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, false)),
        ("keyword.directive".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, false)),
        ("keyword.exception".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(104, 76, 154), None, false, false, true, false)),
        ("keyword.import".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(104, 76, 154), None, false, false, true, false)),
        ("keyword.repeat".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(104, 76, 154), None, false, false, true, false)),
        ("label".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(101, 74, 150), None, false, false, false, false)),
        ("markup.emphasis".into(), Style::new(Color::new(171, 178, 191), None, false, false, true, false)),
        ("markup.environment".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, false)),
        ("markup.environment.name".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, true)),
        ("markup.heading.1.markdown".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, true)),
        ("markup.heading.1.marker.markdown".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, true)),
        ("markup.heading.2.markdown".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, true)),
        ("markup.heading.2.marker.markdown".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, true)),
        ("markup.heading.3.markdown".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, true)),
        ("markup.heading.3.marker.markdown".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, true)),
        ("markup.heading.4.markdown".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, true)),
        ("markup.heading.4.marker.markdown".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, true)),
        ("markup.heading.5.markdown".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, true)),
        ("markup.heading.5.marker.markdown".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, true)),
        ("markup.heading.6.markdown".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, true)),
        ("markup.heading.6.marker.markdown".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, true)),
        ("markup.link".into(), Style::new(Color::new(97, 175, 239), None, false, false, false, false)),
        ("markup.link.url".into(), Style::new(Color::new(86, 182, 194), None, true, false, false, false)),
        ("markup.list".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, false)),
        ("markup.math".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, false)),
        ("markup.raw".into(), Style::new(Color::new(152, 195, 121), None, false, false, false, false)),
        ("markup.strike".into(), Style::new(Color::new(171, 178, 191), None, false, true, false, false)),
        ("markup.strong".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, true)),
        ("markup.underline".into(), Style::new(Color::new(171, 178, 191), None, true, false, false, false)),
        ("method".into(), Style::new(Color::new(77, 162, 179), None, false, false, true, false)),
        ("method.call".into(), Style::new(Color::new(77, 162, 179), None, false, false, true, false)),
        ("module".into(), Style::new(Color::new(229, 192, 123), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(101, 74, 150), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(161, 180, 184), None, false, false, false, false)),
        ("none".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, false)),
        ("note".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(169, 209, 223), None, false, false, false, false)),
        ("parameter.reference".into(), Style::new(Color::new(169, 209, 223), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(198, 120, 221), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(86, 182, 194), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(143, 143, 183), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(101, 101, 104), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(97, 97, 108), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(115, 127, 141), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(83, 117, 126), None, false, false, false, false)),
        ("storageclass.lifetime".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(218, 243, 243), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(218, 243, 243), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(218, 243, 243), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(218, 243, 243), None, false, false, false, false)),
        ("string.special.grammar".into(), Style::new(Color::new(218, 243, 243), None, false, false, false, false)),
        ("string.special.symbol".into(), Style::new(Color::new(86, 182, 194), None, false, false, false, false)),
        ("symbol.grammar.camel".into(), Style::new(Color::new(86, 182, 194), None, false, false, false, false)),
        ("symbol.grammar.lower".into(), Style::new(Color::new(169, 209, 223), None, false, false, false, false)),
        ("symbol.grammar.pascal".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("symbol.grammar.upper".into(), Style::new(Color::new(125, 108, 130), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(133, 193, 193), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(115, 141, 141), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(101, 74, 150), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(59, 70, 73), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.diff.add".into(), Style::new(Color::new(152, 195, 121), None, false, false, false, false)),
        ("text.diff.delete".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, false)),
        ("text.emphasis".into(), Style::new(Color::new(171, 178, 191), None, false, false, true, false)),
        ("text.emphassis".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.environment".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.math".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.reference".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.strike".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.string".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.strong".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, true)),
        ("text.title".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(209, 154, 102), None, false, false, false, true)),
        ("text.todo.checked".into(), Style::new(Color::new(152, 195, 121), None, false, false, true, false)),
        ("text.todo.unchecked".into(), Style::new(Color::new(232, 102, 113), None, false, false, true, false)),
        ("text.underline".into(), Style::new(Color::new(228, 220, 236), None, false, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(72, 133, 133), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(116, 138, 144), None, false, false, false, false)),
        ("type.defintion".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(99, 176, 176), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(148, 194, 210), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(59, 99, 146), None, false, false, false, false)),
        ("variable.member".into(), Style::new(Color::new(86, 182, 194), None, false, false, false, false)),
        ("variable.parameter".into(), Style::new(Color::new(232, 102, 113), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(101, 74, 150), None, false, false, false, false)),
        ("warning".into(), Style::new(Color::new(171, 178, 191), None, false, false, false, false)),
    ]))
}
