//! The 'catppuccin' theme collection in this module was extracted from <https://github.com/catppuccin/nvim> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn latte() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(76, 79, 105), Some(Color::new(239, 241, 245)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(23, 146, 153), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(124, 127, 147), None, false, false, true, false)),
        ("comment.documentation".into(), Style::new(Color::new(124, 127, 147), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(239, 241, 245), Some(Color::new(210, 15, 57)), false, false, false, false)),
        ("comment.hint".into(), Style::new(Color::new(239, 241, 245), Some(Color::new(30, 102, 245)), false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(239, 241, 245), Some(Color::new(30, 102, 245)), false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(239, 241, 245), Some(Color::new(221, 120, 120)), false, false, false, false)),
        ("comment.warning".into(), Style::new(Color::new(239, 241, 245), Some(Color::new(223, 142, 29)), false, false, false, false)),
        ("comment.warning.gitcommit".into(), Style::new(Color::new(223, 142, 29), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(136, 57, 239), None, false, false, true, false)),
        ("constant".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("constant.java".into(), Style::new(Color::new(23, 146, 153), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(32, 159, 181), None, false, false, false, false)),
        ("constructor.lua".into(), Style::new(Color::new(221, 120, 120), None, false, false, false, false)),
        ("constructor.tsx".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, false)),
        ("constructor.typescript".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(210, 15, 57), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(64, 160, 43), None, false, false, false, false)),
        ("error".into(), Style::new(Color::new(210, 15, 57), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("function.builtin.bash".into(), Style::new(Color::new(210, 15, 57), None, false, false, true, false)),
        ("function.call".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(23, 146, 153), None, false, false, false, false)),
        ("function.method".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("function.method.call".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("function.method.call.php".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("function.method.php".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(204, 208, 218), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(76, 79, 105), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(188, 192, 204), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword.conditional".into(), Style::new(Color::new(136, 57, 239), None, false, false, true, false)),
        ("keyword.conditional.ternary".into(), Style::new(Color::new(4, 165, 229), None, false, false, false, false)),
        ("keyword.coroutine".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword.debug".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword.directive".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("keyword.directive.define".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("keyword.exception".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword.export".into(), Style::new(Color::new(4, 165, 229), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword.import".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword.modifier".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(4, 165, 229), None, false, false, false, false)),
        ("keyword.repeat".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword.storage".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("keyword.type".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(32, 159, 181), None, false, false, false, false)),
        ("label.json".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(76, 79, 105), None, false, false, false, false)),
        ("markup.environment".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("markup.environment.name".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, true)),
        ("markup.heading.1.markdown".into(), Style::new(Color::new(210, 15, 57), None, false, false, false, false)),
        ("markup.heading.2.markdown".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("markup.heading.3.markdown".into(), Style::new(Color::new(223, 142, 29), None, false, false, false, false)),
        ("markup.heading.4.markdown".into(), Style::new(Color::new(64, 160, 43), None, false, false, false, false)),
        ("markup.heading.5.markdown".into(), Style::new(Color::new(32, 159, 181), None, false, false, false, false)),
        ("markup.heading.6.markdown".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, false)),
        ("markup.italic".into(), Style::new(Color::new(230, 69, 83), None, false, false, true, false)),
        ("markup.link".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, true)),
        ("markup.link.label".into(), Style::new(Color::new(32, 159, 181), None, false, false, false, false)),
        ("markup.link.url".into(), Style::new(Color::new(220, 138, 120), None, true, false, true, false)),
        ("markup.list".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("markup.list.checked".into(), Style::new(Color::new(64, 160, 43), None, false, false, false, false)),
        ("markup.list.unchecked".into(), Style::new(Color::new(140, 143, 161), None, false, false, false, false)),
        ("markup.math".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("markup.quote".into(), Style::new(Color::new(230, 69, 83), None, false, false, false, true)),
        ("markup.raw".into(), Style::new(Color::new(23, 146, 153), None, false, false, false, false)),
        ("markup.strikethrough".into(), Style::new(Color::new(76, 79, 105), None, false, true, false, false)),
        ("markup.strong".into(), Style::new(Color::new(230, 69, 83), None, false, false, false, true)),
        ("method".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("method.call".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("method.call.php".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("method.php".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(114, 135, 253), None, false, false, true, false)),
        ("module.builtin".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(114, 135, 253), None, false, false, true, false)),
        ("number".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("number.css".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(4, 165, 229), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(230, 69, 83), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, false)),
        ("property.class.css".into(), Style::new(Color::new(223, 142, 29), None, false, false, false, false)),
        ("property.cpp".into(), Style::new(Color::new(76, 79, 105), None, false, false, false, false)),
        ("property.css".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, false)),
        ("property.id.css".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("property.toml".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("property.typescript".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(124, 127, 147), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(124, 127, 147), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(124, 127, 147), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(64, 160, 43), None, false, false, false, false)),
        ("string.documentation".into(), Style::new(Color::new(23, 146, 153), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("string.plain.css".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("string.special.path".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("string.special.path.gitignore".into(), Style::new(Color::new(76, 79, 105), None, false, false, false, false)),
        ("string.special.symbol".into(), Style::new(Color::new(221, 120, 120), None, false, false, false, false)),
        ("string.special.symbol.ruby".into(), Style::new(Color::new(221, 120, 120), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(220, 138, 120), None, true, false, true, false)),
        ("symbol".into(), Style::new(Color::new(221, 120, 120), None, false, false, false, false)),
        ("symbol.ruby".into(), Style::new(Color::new(221, 120, 120), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(23, 146, 153), None, false, false, true, false)),
        ("tag.attribute.tsx".into(), Style::new(Color::new(23, 146, 153), None, false, false, true, false)),
        ("tag.builtin".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(4, 165, 229), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(76, 79, 105), None, false, false, false, false)),
        ("text.danger".into(), Style::new(Color::new(239, 241, 245), Some(Color::new(210, 15, 57)), false, false, false, false)),
        ("text.diff.add".into(), Style::new(Color::new(64, 160, 43), None, false, false, false, false)),
        ("text.diff.delete".into(), Style::new(Color::new(210, 15, 57), None, false, false, false, false)),
        ("text.emphasis".into(), Style::new(Color::new(230, 69, 83), None, false, false, true, false)),
        ("text.environment".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(23, 146, 153), None, false, false, false, false)),
        ("text.math".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, false)),
        ("text.note".into(), Style::new(Color::new(239, 241, 245), Some(Color::new(30, 102, 245)), false, false, false, false)),
        ("text.reference".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, true)),
        ("text.strike".into(), Style::new(Color::new(76, 79, 105), None, false, true, false, false)),
        ("text.strong".into(), Style::new(Color::new(230, 69, 83), None, false, false, false, true)),
        ("text.title".into(), Style::new(Color::new(30, 102, 245), None, false, false, false, true)),
        ("text.title.1.markdown".into(), Style::new(Color::new(210, 15, 57), None, false, false, false, false)),
        ("text.title.2.markdown".into(), Style::new(Color::new(254, 100, 11), None, false, false, false, false)),
        ("text.title.3.markdown".into(), Style::new(Color::new(223, 142, 29), None, false, false, false, false)),
        ("text.title.4.markdown".into(), Style::new(Color::new(64, 160, 43), None, false, false, false, false)),
        ("text.title.5.markdown".into(), Style::new(Color::new(32, 159, 181), None, false, false, false, false)),
        ("text.title.6.markdown".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(239, 241, 245), Some(Color::new(221, 120, 120)), false, false, false, false)),
        ("text.todo.checked".into(), Style::new(Color::new(64, 160, 43), None, false, false, false, false)),
        ("text.todo.unchecked".into(), Style::new(Color::new(140, 143, 161), None, false, false, false, false)),
        ("text.warning".into(), Style::new(Color::new(239, 241, 245), Some(Color::new(223, 142, 29)), false, false, false, false)),
        ("type".into(), Style::new(Color::new(223, 142, 29), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(223, 142, 29), None, false, false, false, false)),
        ("type.builtin.c".into(), Style::new(Color::new(223, 142, 29), None, false, false, false, false)),
        ("type.builtin.cpp".into(), Style::new(Color::new(223, 142, 29), None, false, false, false, false)),
        ("type.css".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(223, 142, 29), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("type.tag.css".into(), Style::new(Color::new(136, 57, 239), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(76, 79, 105), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(210, 15, 57), None, false, false, false, false)),
        ("variable.member".into(), Style::new(Color::new(114, 135, 253), None, false, false, false, false)),
        ("variable.parameter".into(), Style::new(Color::new(230, 69, 83), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(234, 118, 203), None, false, false, false, false)),
    ]))
}

#[rustfmt::skip]
pub fn mocha() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(205, 214, 244), Some(Color::new(30, 30, 46)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(148, 226, 213), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(147, 153, 178), None, false, false, true, false)),
        ("comment.documentation".into(), Style::new(Color::new(147, 153, 178), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(30, 30, 46), Some(Color::new(243, 139, 168)), false, false, false, false)),
        ("comment.hint".into(), Style::new(Color::new(30, 30, 46), Some(Color::new(137, 180, 250)), false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(30, 30, 46), Some(Color::new(137, 180, 250)), false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(30, 30, 46), Some(Color::new(242, 205, 205)), false, false, false, false)),
        ("comment.warning".into(), Style::new(Color::new(30, 30, 46), Some(Color::new(249, 226, 175)), false, false, false, false)),
        ("comment.warning.gitcommit".into(), Style::new(Color::new(249, 226, 175), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(203, 166, 247), None, false, false, true, false)),
        ("constant".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("constant.java".into(), Style::new(Color::new(148, 226, 213), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(116, 199, 236), None, false, false, false, false)),
        ("constructor.lua".into(), Style::new(Color::new(242, 205, 205), None, false, false, false, false)),
        ("constructor.tsx".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, false)),
        ("constructor.typescript".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(243, 139, 168), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(166, 227, 161), None, false, false, false, false)),
        ("error".into(), Style::new(Color::new(243, 139, 168), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("function.builtin.bash".into(), Style::new(Color::new(243, 139, 168), None, false, false, true, false)),
        ("function.call".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(148, 226, 213), None, false, false, false, false)),
        ("function.method".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("function.method.call".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("function.method.call.php".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("function.method.php".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(49, 50, 68), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(205, 214, 244), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(69, 71, 90), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword.conditional".into(), Style::new(Color::new(203, 166, 247), None, false, false, true, false)),
        ("keyword.conditional.ternary".into(), Style::new(Color::new(137, 220, 235), None, false, false, false, false)),
        ("keyword.coroutine".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword.debug".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword.directive".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("keyword.directive.define".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("keyword.exception".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword.export".into(), Style::new(Color::new(137, 220, 235), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword.import".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword.modifier".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(137, 220, 235), None, false, false, false, false)),
        ("keyword.repeat".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword.storage".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("keyword.type".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(116, 199, 236), None, false, false, false, false)),
        ("label.json".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(205, 214, 244), None, false, false, false, false)),
        ("markup.environment".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("markup.environment.name".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, true)),
        ("markup.heading.1.markdown".into(), Style::new(Color::new(243, 139, 168), None, false, false, false, false)),
        ("markup.heading.2.markdown".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("markup.heading.3.markdown".into(), Style::new(Color::new(249, 226, 175), None, false, false, false, false)),
        ("markup.heading.4.markdown".into(), Style::new(Color::new(166, 227, 161), None, false, false, false, false)),
        ("markup.heading.5.markdown".into(), Style::new(Color::new(116, 199, 236), None, false, false, false, false)),
        ("markup.heading.6.markdown".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, false)),
        ("markup.italic".into(), Style::new(Color::new(235, 160, 172), None, false, false, true, false)),
        ("markup.link".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, true)),
        ("markup.link.label".into(), Style::new(Color::new(116, 199, 236), None, false, false, false, false)),
        ("markup.link.url".into(), Style::new(Color::new(245, 224, 220), None, true, false, true, false)),
        ("markup.list".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("markup.list.checked".into(), Style::new(Color::new(166, 227, 161), None, false, false, false, false)),
        ("markup.list.unchecked".into(), Style::new(Color::new(127, 132, 156), None, false, false, false, false)),
        ("markup.math".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("markup.quote".into(), Style::new(Color::new(235, 160, 172), None, false, false, false, true)),
        ("markup.raw".into(), Style::new(Color::new(148, 226, 213), None, false, false, false, false)),
        ("markup.strikethrough".into(), Style::new(Color::new(205, 214, 244), None, false, true, false, false)),
        ("markup.strong".into(), Style::new(Color::new(235, 160, 172), None, false, false, false, true)),
        ("method".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("method.call".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("method.call.php".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("method.php".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(180, 190, 254), None, false, false, true, false)),
        ("module.builtin".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(180, 190, 254), None, false, false, true, false)),
        ("number".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("number.css".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(137, 220, 235), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(235, 160, 172), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, false)),
        ("property.class.css".into(), Style::new(Color::new(249, 226, 175), None, false, false, false, false)),
        ("property.cpp".into(), Style::new(Color::new(205, 214, 244), None, false, false, false, false)),
        ("property.css".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, false)),
        ("property.id.css".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("property.toml".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("property.typescript".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(147, 153, 178), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(147, 153, 178), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(147, 153, 178), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(166, 227, 161), None, false, false, false, false)),
        ("string.documentation".into(), Style::new(Color::new(148, 226, 213), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("string.plain.css".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("string.special.path".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("string.special.path.gitignore".into(), Style::new(Color::new(205, 214, 244), None, false, false, false, false)),
        ("string.special.symbol".into(), Style::new(Color::new(242, 205, 205), None, false, false, false, false)),
        ("string.special.symbol.ruby".into(), Style::new(Color::new(242, 205, 205), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(245, 224, 220), None, true, false, true, false)),
        ("symbol".into(), Style::new(Color::new(242, 205, 205), None, false, false, false, false)),
        ("symbol.ruby".into(), Style::new(Color::new(242, 205, 205), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(148, 226, 213), None, false, false, true, false)),
        ("tag.attribute.tsx".into(), Style::new(Color::new(148, 226, 213), None, false, false, true, false)),
        ("tag.builtin".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(137, 220, 235), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(205, 214, 244), None, false, false, false, false)),
        ("text.danger".into(), Style::new(Color::new(30, 30, 46), Some(Color::new(243, 139, 168)), false, false, false, false)),
        ("text.diff.add".into(), Style::new(Color::new(166, 227, 161), None, false, false, false, false)),
        ("text.diff.delete".into(), Style::new(Color::new(243, 139, 168), None, false, false, false, false)),
        ("text.emphasis".into(), Style::new(Color::new(235, 160, 172), None, false, false, true, false)),
        ("text.environment".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(148, 226, 213), None, false, false, false, false)),
        ("text.math".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, false)),
        ("text.note".into(), Style::new(Color::new(30, 30, 46), Some(Color::new(137, 180, 250)), false, false, false, false)),
        ("text.reference".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, true)),
        ("text.strike".into(), Style::new(Color::new(205, 214, 244), None, false, true, false, false)),
        ("text.strong".into(), Style::new(Color::new(235, 160, 172), None, false, false, false, true)),
        ("text.title".into(), Style::new(Color::new(137, 180, 250), None, false, false, false, true)),
        ("text.title.1.markdown".into(), Style::new(Color::new(243, 139, 168), None, false, false, false, false)),
        ("text.title.2.markdown".into(), Style::new(Color::new(250, 179, 135), None, false, false, false, false)),
        ("text.title.3.markdown".into(), Style::new(Color::new(249, 226, 175), None, false, false, false, false)),
        ("text.title.4.markdown".into(), Style::new(Color::new(166, 227, 161), None, false, false, false, false)),
        ("text.title.5.markdown".into(), Style::new(Color::new(116, 199, 236), None, false, false, false, false)),
        ("text.title.6.markdown".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(30, 30, 46), Some(Color::new(242, 205, 205)), false, false, false, false)),
        ("text.todo.checked".into(), Style::new(Color::new(166, 227, 161), None, false, false, false, false)),
        ("text.todo.unchecked".into(), Style::new(Color::new(127, 132, 156), None, false, false, false, false)),
        ("text.warning".into(), Style::new(Color::new(30, 30, 46), Some(Color::new(249, 226, 175)), false, false, false, false)),
        ("type".into(), Style::new(Color::new(249, 226, 175), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(249, 226, 175), None, false, false, false, false)),
        ("type.builtin.c".into(), Style::new(Color::new(249, 226, 175), None, false, false, false, false)),
        ("type.builtin.cpp".into(), Style::new(Color::new(249, 226, 175), None, false, false, false, false)),
        ("type.css".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(249, 226, 175), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("type.tag.css".into(), Style::new(Color::new(203, 166, 247), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(205, 214, 244), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(243, 139, 168), None, false, false, false, false)),
        ("variable.member".into(), Style::new(Color::new(180, 190, 254), None, false, false, false, false)),
        ("variable.parameter".into(), Style::new(Color::new(235, 160, 172), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(245, 194, 231), None, false, false, false, false)),
    ]))
}

#[rustfmt::skip]
pub fn frappe() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(198, 208, 245), Some(Color::new(48, 52, 70)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(129, 200, 190), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(148, 156, 187), None, false, false, true, false)),
        ("comment.documentation".into(), Style::new(Color::new(148, 156, 187), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(48, 52, 70), Some(Color::new(231, 130, 132)), false, false, false, false)),
        ("comment.hint".into(), Style::new(Color::new(48, 52, 70), Some(Color::new(140, 170, 238)), false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(48, 52, 70), Some(Color::new(140, 170, 238)), false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(48, 52, 70), Some(Color::new(238, 190, 190)), false, false, false, false)),
        ("comment.warning".into(), Style::new(Color::new(48, 52, 70), Some(Color::new(229, 200, 144)), false, false, false, false)),
        ("comment.warning.gitcommit".into(), Style::new(Color::new(229, 200, 144), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(202, 158, 230), None, false, false, true, false)),
        ("constant".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("constant.java".into(), Style::new(Color::new(129, 200, 190), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(133, 193, 220), None, false, false, false, false)),
        ("constructor.lua".into(), Style::new(Color::new(238, 190, 190), None, false, false, false, false)),
        ("constructor.tsx".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, false)),
        ("constructor.typescript".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(231, 130, 132), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(166, 209, 137), None, false, false, false, false)),
        ("error".into(), Style::new(Color::new(231, 130, 132), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("function.builtin.bash".into(), Style::new(Color::new(231, 130, 132), None, false, false, true, false)),
        ("function.call".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(129, 200, 190), None, false, false, false, false)),
        ("function.method".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("function.method.call".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("function.method.call.php".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("function.method.php".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(65, 69, 89), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(198, 208, 245), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(81, 87, 109), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword.conditional".into(), Style::new(Color::new(202, 158, 230), None, false, false, true, false)),
        ("keyword.conditional.ternary".into(), Style::new(Color::new(153, 209, 219), None, false, false, false, false)),
        ("keyword.coroutine".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword.debug".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword.directive".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("keyword.directive.define".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("keyword.exception".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword.export".into(), Style::new(Color::new(153, 209, 219), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword.import".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword.modifier".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(153, 209, 219), None, false, false, false, false)),
        ("keyword.repeat".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword.storage".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("keyword.type".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(133, 193, 220), None, false, false, false, false)),
        ("label.json".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(198, 208, 245), None, false, false, false, false)),
        ("markup.environment".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("markup.environment.name".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, true)),
        ("markup.heading.1.markdown".into(), Style::new(Color::new(231, 130, 132), None, false, false, false, false)),
        ("markup.heading.2.markdown".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("markup.heading.3.markdown".into(), Style::new(Color::new(229, 200, 144), None, false, false, false, false)),
        ("markup.heading.4.markdown".into(), Style::new(Color::new(166, 209, 137), None, false, false, false, false)),
        ("markup.heading.5.markdown".into(), Style::new(Color::new(133, 193, 220), None, false, false, false, false)),
        ("markup.heading.6.markdown".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, false)),
        ("markup.italic".into(), Style::new(Color::new(234, 153, 156), None, false, false, true, false)),
        ("markup.link".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, true)),
        ("markup.link.label".into(), Style::new(Color::new(133, 193, 220), None, false, false, false, false)),
        ("markup.link.url".into(), Style::new(Color::new(242, 213, 207), None, true, false, true, false)),
        ("markup.list".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("markup.list.checked".into(), Style::new(Color::new(166, 209, 137), None, false, false, false, false)),
        ("markup.list.unchecked".into(), Style::new(Color::new(131, 139, 167), None, false, false, false, false)),
        ("markup.math".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("markup.quote".into(), Style::new(Color::new(234, 153, 156), None, false, false, false, true)),
        ("markup.raw".into(), Style::new(Color::new(129, 200, 190), None, false, false, false, false)),
        ("markup.strikethrough".into(), Style::new(Color::new(198, 208, 245), None, false, true, false, false)),
        ("markup.strong".into(), Style::new(Color::new(234, 153, 156), None, false, false, false, true)),
        ("method".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("method.call".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("method.call.php".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("method.php".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(186, 187, 241), None, false, false, true, false)),
        ("module.builtin".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(186, 187, 241), None, false, false, true, false)),
        ("number".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("number.css".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(153, 209, 219), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(234, 153, 156), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, false)),
        ("property.class.css".into(), Style::new(Color::new(229, 200, 144), None, false, false, false, false)),
        ("property.cpp".into(), Style::new(Color::new(198, 208, 245), None, false, false, false, false)),
        ("property.css".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, false)),
        ("property.id.css".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("property.toml".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("property.typescript".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(148, 156, 187), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(148, 156, 187), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(148, 156, 187), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(166, 209, 137), None, false, false, false, false)),
        ("string.documentation".into(), Style::new(Color::new(129, 200, 190), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("string.plain.css".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("string.special.path".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("string.special.path.gitignore".into(), Style::new(Color::new(198, 208, 245), None, false, false, false, false)),
        ("string.special.symbol".into(), Style::new(Color::new(238, 190, 190), None, false, false, false, false)),
        ("string.special.symbol.ruby".into(), Style::new(Color::new(238, 190, 190), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(242, 213, 207), None, true, false, true, false)),
        ("symbol".into(), Style::new(Color::new(238, 190, 190), None, false, false, false, false)),
        ("symbol.ruby".into(), Style::new(Color::new(238, 190, 190), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(129, 200, 190), None, false, false, true, false)),
        ("tag.attribute.tsx".into(), Style::new(Color::new(129, 200, 190), None, false, false, true, false)),
        ("tag.builtin".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(153, 209, 219), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(198, 208, 245), None, false, false, false, false)),
        ("text.danger".into(), Style::new(Color::new(48, 52, 70), Some(Color::new(231, 130, 132)), false, false, false, false)),
        ("text.diff.add".into(), Style::new(Color::new(166, 209, 137), None, false, false, false, false)),
        ("text.diff.delete".into(), Style::new(Color::new(231, 130, 132), None, false, false, false, false)),
        ("text.emphasis".into(), Style::new(Color::new(234, 153, 156), None, false, false, true, false)),
        ("text.environment".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(129, 200, 190), None, false, false, false, false)),
        ("text.math".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, false)),
        ("text.note".into(), Style::new(Color::new(48, 52, 70), Some(Color::new(140, 170, 238)), false, false, false, false)),
        ("text.reference".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, true)),
        ("text.strike".into(), Style::new(Color::new(198, 208, 245), None, false, true, false, false)),
        ("text.strong".into(), Style::new(Color::new(234, 153, 156), None, false, false, false, true)),
        ("text.title".into(), Style::new(Color::new(140, 170, 238), None, false, false, false, true)),
        ("text.title.1.markdown".into(), Style::new(Color::new(231, 130, 132), None, false, false, false, false)),
        ("text.title.2.markdown".into(), Style::new(Color::new(239, 159, 118), None, false, false, false, false)),
        ("text.title.3.markdown".into(), Style::new(Color::new(229, 200, 144), None, false, false, false, false)),
        ("text.title.4.markdown".into(), Style::new(Color::new(166, 209, 137), None, false, false, false, false)),
        ("text.title.5.markdown".into(), Style::new(Color::new(133, 193, 220), None, false, false, false, false)),
        ("text.title.6.markdown".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(48, 52, 70), Some(Color::new(238, 190, 190)), false, false, false, false)),
        ("text.todo.checked".into(), Style::new(Color::new(166, 209, 137), None, false, false, false, false)),
        ("text.todo.unchecked".into(), Style::new(Color::new(131, 139, 167), None, false, false, false, false)),
        ("text.warning".into(), Style::new(Color::new(48, 52, 70), Some(Color::new(229, 200, 144)), false, false, false, false)),
        ("type".into(), Style::new(Color::new(229, 200, 144), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(229, 200, 144), None, false, false, false, false)),
        ("type.builtin.c".into(), Style::new(Color::new(229, 200, 144), None, false, false, false, false)),
        ("type.builtin.cpp".into(), Style::new(Color::new(229, 200, 144), None, false, false, false, false)),
        ("type.css".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(229, 200, 144), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("type.tag.css".into(), Style::new(Color::new(202, 158, 230), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(198, 208, 245), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(231, 130, 132), None, false, false, false, false)),
        ("variable.member".into(), Style::new(Color::new(186, 187, 241), None, false, false, false, false)),
        ("variable.parameter".into(), Style::new(Color::new(234, 153, 156), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(244, 184, 228), None, false, false, false, false)),
    ]))
}

#[rustfmt::skip]
pub fn macchiato() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(202, 211, 245), Some(Color::new(36, 39, 58)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(139, 213, 202), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(147, 154, 183), None, false, false, true, false)),
        ("comment.documentation".into(), Style::new(Color::new(147, 154, 183), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(36, 39, 58), Some(Color::new(237, 135, 150)), false, false, false, false)),
        ("comment.hint".into(), Style::new(Color::new(36, 39, 58), Some(Color::new(138, 173, 244)), false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(36, 39, 58), Some(Color::new(138, 173, 244)), false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(36, 39, 58), Some(Color::new(240, 198, 198)), false, false, false, false)),
        ("comment.warning".into(), Style::new(Color::new(36, 39, 58), Some(Color::new(238, 212, 159)), false, false, false, false)),
        ("comment.warning.gitcommit".into(), Style::new(Color::new(238, 212, 159), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(198, 160, 246), None, false, false, true, false)),
        ("constant".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("constant.java".into(), Style::new(Color::new(139, 213, 202), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(125, 196, 228), None, false, false, false, false)),
        ("constructor.lua".into(), Style::new(Color::new(240, 198, 198), None, false, false, false, false)),
        ("constructor.tsx".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, false)),
        ("constructor.typescript".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(237, 135, 150), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(166, 218, 149), None, false, false, false, false)),
        ("error".into(), Style::new(Color::new(237, 135, 150), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("function.builtin.bash".into(), Style::new(Color::new(237, 135, 150), None, false, false, true, false)),
        ("function.call".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(139, 213, 202), None, false, false, false, false)),
        ("function.method".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("function.method.call".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("function.method.call.php".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("function.method.php".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(54, 58, 79), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(202, 211, 245), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(73, 77, 100), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword.conditional".into(), Style::new(Color::new(198, 160, 246), None, false, false, true, false)),
        ("keyword.conditional.ternary".into(), Style::new(Color::new(145, 215, 227), None, false, false, false, false)),
        ("keyword.coroutine".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword.debug".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword.directive".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("keyword.directive.define".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("keyword.exception".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword.export".into(), Style::new(Color::new(145, 215, 227), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword.import".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword.modifier".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(145, 215, 227), None, false, false, false, false)),
        ("keyword.repeat".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword.storage".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("keyword.type".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(125, 196, 228), None, false, false, false, false)),
        ("label.json".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(202, 211, 245), None, false, false, false, false)),
        ("markup.environment".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("markup.environment.name".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, true)),
        ("markup.heading.1.markdown".into(), Style::new(Color::new(237, 135, 150), None, false, false, false, false)),
        ("markup.heading.2.markdown".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("markup.heading.3.markdown".into(), Style::new(Color::new(238, 212, 159), None, false, false, false, false)),
        ("markup.heading.4.markdown".into(), Style::new(Color::new(166, 218, 149), None, false, false, false, false)),
        ("markup.heading.5.markdown".into(), Style::new(Color::new(125, 196, 228), None, false, false, false, false)),
        ("markup.heading.6.markdown".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, false)),
        ("markup.italic".into(), Style::new(Color::new(238, 153, 160), None, false, false, true, false)),
        ("markup.link".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, true)),
        ("markup.link.label".into(), Style::new(Color::new(125, 196, 228), None, false, false, false, false)),
        ("markup.link.url".into(), Style::new(Color::new(244, 219, 214), None, true, false, true, false)),
        ("markup.list".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("markup.list.checked".into(), Style::new(Color::new(166, 218, 149), None, false, false, false, false)),
        ("markup.list.unchecked".into(), Style::new(Color::new(128, 135, 162), None, false, false, false, false)),
        ("markup.math".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("markup.quote".into(), Style::new(Color::new(238, 153, 160), None, false, false, false, true)),
        ("markup.raw".into(), Style::new(Color::new(139, 213, 202), None, false, false, false, false)),
        ("markup.strikethrough".into(), Style::new(Color::new(202, 211, 245), None, false, true, false, false)),
        ("markup.strong".into(), Style::new(Color::new(238, 153, 160), None, false, false, false, true)),
        ("method".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("method.call".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("method.call.php".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("method.php".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(183, 189, 248), None, false, false, true, false)),
        ("module.builtin".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(183, 189, 248), None, false, false, true, false)),
        ("number".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("number.css".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(145, 215, 227), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(238, 153, 160), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, false)),
        ("property.class.css".into(), Style::new(Color::new(238, 212, 159), None, false, false, false, false)),
        ("property.cpp".into(), Style::new(Color::new(202, 211, 245), None, false, false, false, false)),
        ("property.css".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, false)),
        ("property.id.css".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("property.toml".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("property.typescript".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(147, 154, 183), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(147, 154, 183), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(147, 154, 183), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(166, 218, 149), None, false, false, false, false)),
        ("string.documentation".into(), Style::new(Color::new(139, 213, 202), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("string.plain.css".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("string.special.path".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("string.special.path.gitignore".into(), Style::new(Color::new(202, 211, 245), None, false, false, false, false)),
        ("string.special.symbol".into(), Style::new(Color::new(240, 198, 198), None, false, false, false, false)),
        ("string.special.symbol.ruby".into(), Style::new(Color::new(240, 198, 198), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(244, 219, 214), None, true, false, true, false)),
        ("symbol".into(), Style::new(Color::new(240, 198, 198), None, false, false, false, false)),
        ("symbol.ruby".into(), Style::new(Color::new(240, 198, 198), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(139, 213, 202), None, false, false, true, false)),
        ("tag.attribute.tsx".into(), Style::new(Color::new(139, 213, 202), None, false, false, true, false)),
        ("tag.builtin".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(145, 215, 227), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(202, 211, 245), None, false, false, false, false)),
        ("text.danger".into(), Style::new(Color::new(36, 39, 58), Some(Color::new(237, 135, 150)), false, false, false, false)),
        ("text.diff.add".into(), Style::new(Color::new(166, 218, 149), None, false, false, false, false)),
        ("text.diff.delete".into(), Style::new(Color::new(237, 135, 150), None, false, false, false, false)),
        ("text.emphasis".into(), Style::new(Color::new(238, 153, 160), None, false, false, true, false)),
        ("text.environment".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(139, 213, 202), None, false, false, false, false)),
        ("text.math".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, false)),
        ("text.note".into(), Style::new(Color::new(36, 39, 58), Some(Color::new(138, 173, 244)), false, false, false, false)),
        ("text.reference".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, true)),
        ("text.strike".into(), Style::new(Color::new(202, 211, 245), None, false, true, false, false)),
        ("text.strong".into(), Style::new(Color::new(238, 153, 160), None, false, false, false, true)),
        ("text.title".into(), Style::new(Color::new(138, 173, 244), None, false, false, false, true)),
        ("text.title.1.markdown".into(), Style::new(Color::new(237, 135, 150), None, false, false, false, false)),
        ("text.title.2.markdown".into(), Style::new(Color::new(245, 169, 127), None, false, false, false, false)),
        ("text.title.3.markdown".into(), Style::new(Color::new(238, 212, 159), None, false, false, false, false)),
        ("text.title.4.markdown".into(), Style::new(Color::new(166, 218, 149), None, false, false, false, false)),
        ("text.title.5.markdown".into(), Style::new(Color::new(125, 196, 228), None, false, false, false, false)),
        ("text.title.6.markdown".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(36, 39, 58), Some(Color::new(240, 198, 198)), false, false, false, false)),
        ("text.todo.checked".into(), Style::new(Color::new(166, 218, 149), None, false, false, false, false)),
        ("text.todo.unchecked".into(), Style::new(Color::new(128, 135, 162), None, false, false, false, false)),
        ("text.warning".into(), Style::new(Color::new(36, 39, 58), Some(Color::new(238, 212, 159)), false, false, false, false)),
        ("type".into(), Style::new(Color::new(238, 212, 159), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(238, 212, 159), None, false, false, false, false)),
        ("type.builtin.c".into(), Style::new(Color::new(238, 212, 159), None, false, false, false, false)),
        ("type.builtin.cpp".into(), Style::new(Color::new(238, 212, 159), None, false, false, false, false)),
        ("type.css".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(238, 212, 159), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("type.tag.css".into(), Style::new(Color::new(198, 160, 246), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(202, 211, 245), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(237, 135, 150), None, false, false, false, false)),
        ("variable.member".into(), Style::new(Color::new(183, 189, 248), None, false, false, false, false)),
        ("variable.parameter".into(), Style::new(Color::new(238, 153, 160), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(245, 189, 230), None, false, false, false, false)),
    ]))
}
