//! The 'dracula' theme collection in this module was extracted from <https://github.com/dracula/vim> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn dracula() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(248, 248, 242), Some(Color::new(40, 42, 54)), false, false, false, false)),
        ("annotation".into(), Style::new(Color::new(241, 250, 140), None, false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(80, 250, 123), None, false, false, true, false)),
        ("attribute.builtin".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(189, 147, 249), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(98, 114, 164), None, false, false, false, false)),
        ("comment.error".into(), Style::new(Color::new(255, 85, 85), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(139, 233, 253), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(139, 233, 253), None, false, false, false, true)),
        ("comment.warning".into(), Style::new(Color::new(255, 184, 108), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(189, 147, 249), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(189, 147, 249), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(139, 233, 253), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(179, 246, 192), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(189, 147, 249), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(255, 184, 108), None, false, false, false, false)),
        ("funcion.macro".into(), Style::new(Color::new(80, 250, 123), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(80, 250, 123), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(139, 233, 253), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(66, 68, 80), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(98, 114, 164), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(66, 68, 80), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(189, 147, 249), None, false, false, true, false)),
        ("markup".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(241, 250, 140), None, false, false, false, false)),
        ("markup.link".into(), Style::new(Color::new(248, 248, 242), None, true, false, false, false)),
        ("markup.link.label".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("markup.link.uri".into(), Style::new(Color::new(241, 250, 140), None, false, false, false, false)),
        ("markup.list".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("markup.raw".into(), Style::new(Color::new(241, 250, 140), None, false, false, false, false)),
        ("markup.strikethrough".into(), Style::new(Color::new(248, 248, 242), None, false, true, false, false)),
        ("markup.strong".into(), Style::new(Color::new(248, 248, 242), None, false, false, false, true)),
        ("markup.underline".into(), Style::new(Color::new(248, 248, 242), None, true, false, false, false)),
        ("module".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(189, 147, 249), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(189, 147, 249), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(255, 184, 108), None, false, false, true, false)),
        ("parameter.reference".into(), Style::new(Color::new(255, 184, 108), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(248, 248, 242), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(248, 248, 242), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(248, 248, 242), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(248, 248, 242), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(241, 250, 140), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("string.special.symbol".into(), Style::new(Color::new(189, 147, 249), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(248, 248, 242), None, true, false, false, false)),
        ("symbol".into(), Style::new(Color::new(189, 147, 249), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(139, 233, 253), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(80, 250, 123), None, false, false, true, false)),
        ("tag.builtin".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(248, 248, 242), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(248, 248, 242), None, false, false, false, false)),
        ("text.diff.add".into(), Style::new(Color::new(80, 250, 123), None, false, false, false, false)),
        ("text.diff.delete".into(), Style::new(Color::new(255, 85, 85), Some(Color::new(33, 34, 44)), false, false, false, false)),
        ("text.emphasis".into(), Style::new(Color::new(248, 248, 242), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(241, 250, 140), None, false, false, false, false)),
        ("text.strong".into(), Style::new(Color::new(248, 248, 242), None, false, false, false, true)),
        ("text.title".into(), Style::new(Color::new(241, 250, 140), None, false, false, false, false)),
        ("text.underline".into(), Style::new(Color::new(248, 248, 242), None, true, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(241, 250, 140), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(139, 233, 253), None, false, false, true, false)),
        ("type.builtin".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(248, 248, 242), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(189, 147, 249), None, false, false, true, false)),
        ("variable.member".into(), Style::new(Color::new(255, 184, 108), None, false, false, false, false)),
        ("variable.parameter".into(), Style::new(Color::new(255, 184, 108), None, false, false, true, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(255, 121, 198), None, false, false, false, false)),
    ]))
}
