//! The 'dracula' theme collection in this module was extracted from <https://github.com/dracula/vim> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn dracula() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(244, 243, 242), Some(Color::new(33, 34, 44)), false, false, false, false)),
        ("annotation".into(), Style::new(Color::new(255, 85, 95), None, false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(241, 250, 135), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(255, 121, 193), None, false, false, true, false)),
        ("character".into(), Style::new(Color::new(221, 207, 191), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(255, 121, 199), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(100, 118, 166), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(239, 112, 160), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(152, 118, 170), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(152, 118, 170), None, false, false, false, true)),
        ("constant.macro".into(), Style::new(Color::new(255, 85, 95), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(189, 148, 244), None, false, false, false, false)),
        ("debug".into(), Style::new(Color::new(255, 85, 95), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(255, 121, 199), None, false, false, false, false)),
        ("emphasis".into(), Style::new(Color::new(241, 250, 135), None, false, false, false, true)),
        ("exception".into(), Style::new(Color::new(158, 113, 207), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(147, 115, 165), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(255, 121, 193), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(95, 246, 125), None, false, false, false, true)),
        ("function.builtin".into(), Style::new(Color::new(95, 246, 125), None, false, false, false, true)),
        ("function.call".into(), Style::new(Color::new(95, 246, 125), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(139, 228, 241), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(4, 209, 249), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(254, 87, 192), None, false, false, false, true)),
        ("keyword.function".into(), Style::new(Color::new(254, 199, 80), None, false, false, false, true)),
        ("keyword.operator".into(), Style::new(Color::new(139, 228, 241), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(254, 87, 192), None, false, false, false, true)),
        ("label".into(), Style::new(Color::new(26, 173, 22), None, false, false, false, false)),
        ("macro".into(), Style::new(Color::new(139, 228, 241), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(127, 230, 93), None, false, false, false, true)),
        ("method.call".into(), Style::new(Color::new(127, 230, 93), None, false, false, false, true)),
        ("namespace".into(), Style::new(Color::new(251, 236, 159), None, false, false, false, false)),
        ("none".into(), Style::new(Color::new(100, 118, 166), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(189, 148, 244), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(139, 228, 241), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(218, 113, 194), None, false, false, false, true)),
        ("parameter.reference".into(), Style::new(Color::new(241, 250, 135), None, false, false, false, true)),
        ("preproc".into(), Style::new(Color::new(189, 148, 244), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(147, 115, 165), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(16, 174, 248), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(248, 246, 170), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(139, 228, 241), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(64, 142, 248), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(239, 112, 160), None, false, false, false, true)),
        ("storageclass".into(), Style::new(Color::new(250, 128, 114), None, false, false, false, false)),
        ("strike".into(), Style::new(Color::new(161, 171, 224), None, false, true, false, false)),
        ("string".into(), Style::new(Color::new(250, 199, 57), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(97, 87, 82), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(241, 155, 182), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(255, 121, 199), None, false, false, false, false)),
        ("symbol".into(), Style::new(Color::new(169, 237, 255), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(152, 238, 100), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(245, 226, 237), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(16, 174, 248), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(244, 243, 242), Some(Color::new(33, 34, 44)), false, false, false, false)),
        ("text.danger".into(), Style::new(Color::new(255, 0, 0), None, false, false, false, false)),
        ("text.environment".into(), Style::new(Color::new(139, 228, 241), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(4, 209, 249), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(250, 199, 57), None, false, false, false, false)),
        ("text.literal.markdown".into(), Style::new(Color::new(244, 243, 242), Some(Color::new(33, 34, 44)), false, false, false, false)),
        ("text.literal.markdown_inline".into(), Style::new(Color::new(255, 85, 95), None, false, false, false, false)),
        ("text.math".into(), Style::new(Color::new(255, 85, 95), None, false, false, false, false)),
        ("text.note".into(), Style::new(Color::new(100, 118, 166), None, false, false, false, false)),
        ("text.reference".into(), Style::new(Color::new(152, 118, 170), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(254, 248, 242), None, false, false, false, true)),
        ("text.todo".into(), Style::new(Color::new(241, 250, 135), Some(Color::new(40, 42, 54)), false, false, true, true)),
        ("text.todo.checked".into(), Style::new(Color::new(100, 118, 166), None, false, false, false, false)),
        ("text.todo.unchecked".into(), Style::new(Color::new(241, 250, 135), Some(Color::new(40, 42, 54)), false, false, true, true)),
        ("text.uri".into(), Style::new(Color::new(128, 203, 196), None, false, false, false, false)),
        ("text.warning".into(), Style::new(Color::new(241, 250, 135), None, false, false, false, false)),
        ("title".into(), Style::new(Color::new(254, 248, 242), None, false, false, false, true)),
        ("type".into(), Style::new(Color::new(4, 209, 249), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(174, 129, 239), None, false, false, false, true)),
        ("type.definition".into(), Style::new(Color::new(249, 39, 114), None, false, false, false, false)),
        ("type.deinition".into(), Style::new(Color::new(249, 39, 114), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(4, 209, 249), None, false, false, false, false)),
        ("underline".into(), Style::new(Color::new(244, 243, 242), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(245, 226, 237), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(245, 226, 237), None, false, false, false, false)),
    ]))
}
