//! The 'everforest' theme collection in this module was extracted from <https://github.com/sainnhe/everforest> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn dark() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(236, 225, 215), Some(Color::new(41, 37, 34)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(133, 182, 149), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(207, 155, 194), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(127, 145, 178), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(193, 167, 142), None, false, false, true, false)),
        ("comment.documentation".into(), Style::new(Color::new(193, 167, 142), None, false, false, false, false)),
        ("comment.error".into(), Style::new(Color::new(193, 167, 142), None, false, false, false, true)),
        ("comment.note".into(), Style::new(Color::new(193, 167, 142), None, false, false, false, true)),
        ("comment.todo".into(), Style::new(Color::new(193, 167, 142), None, false, false, false, true)),
        ("comment.warning".into(), Style::new(Color::new(193, 167, 142), None, false, false, false, true)),
        ("constant".into(), Style::new(Color::new(236, 225, 215), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(179, 128, 176), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(179, 128, 176), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(64, 58, 54), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(134, 116, 98), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(64, 58, 54), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(228, 155, 93), None, false, false, false, false)),
        ("keyword.directive".into(), Style::new(Color::new(133, 182, 149), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(133, 182, 149), None, false, false, false, false)),
        ("keyword.import".into(), Style::new(Color::new(133, 182, 149), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(137, 179, 182), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(228, 155, 93), None, false, false, false, false)),
        ("markup.heading.2".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("markup.heading.3".into(), Style::new(Color::new(133, 182, 149), None, false, false, false, false)),
        ("markup.heading.4".into(), Style::new(Color::new(137, 179, 182), None, false, false, false, false)),
        ("markup.link.url".into(), Style::new(Color::new(127, 145, 178), None, false, false, false, false)),
        ("markup.list".into(), Style::new(Color::new(139, 116, 73), None, false, false, false, false)),
        ("markup.quote".into(), Style::new(Color::new(193, 167, 142), None, false, false, true, false)),
        ("markup.raw".into(), Style::new(Color::new(193, 167, 142), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(236, 225, 215), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(236, 225, 215), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(207, 155, 194), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(207, 155, 194), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(212, 119, 102), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(236, 225, 215), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(139, 116, 73), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(189, 129, 131), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(163, 169, 206), None, false, false, true, false)),
        ("string.documentation".into(), Style::new(Color::new(163, 169, 206), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(127, 145, 178), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(163, 169, 206), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(137, 179, 182), None, false, false, false, false)),
        ("string.special.path".into(), Style::new(Color::new(127, 145, 178), None, false, false, false, false)),
        ("string.special.symbol".into(), Style::new(Color::new(236, 225, 215), None, false, false, true, false)),
        ("string.special.url".into(), Style::new(Color::new(127, 145, 178), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(137, 179, 182), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(139, 116, 73), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(123, 150, 149), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(228, 155, 93), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(236, 225, 215), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(236, 225, 215), None, false, false, true, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(235, 192, 109), None, false, false, false, false)),
    ]))
}

#[rustfmt::skip]
pub fn light() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(84, 67, 58), Some(Color::new(241, 241, 241)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(58, 104, 74), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(144, 65, 128), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(120, 146, 189), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(125, 102, 88), None, false, false, true, false)),
        ("comment.documentation".into(), Style::new(Color::new(125, 102, 88), None, false, false, false, false)),
        ("comment.error".into(), Style::new(Color::new(125, 102, 88), None, false, false, false, true)),
        ("comment.note".into(), Style::new(Color::new(125, 102, 88), None, false, false, false, true)),
        ("comment.todo".into(), Style::new(Color::new(125, 102, 88), None, false, false, false, true)),
        ("comment.warning".into(), Style::new(Color::new(125, 102, 88), None, false, false, false, true)),
        ("constant".into(), Style::new(Color::new(84, 67, 58), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(190, 121, 187), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(190, 121, 187), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(217, 211, 206), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(169, 138, 120), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(217, 211, 206), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(188, 92, 0), None, false, false, false, false)),
        ("keyword.directive".into(), Style::new(Color::new(58, 104, 74), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(58, 104, 74), None, false, false, false, false)),
        ("keyword.import".into(), Style::new(Color::new(58, 104, 74), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(61, 101, 104), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(188, 92, 0), None, false, false, false, false)),
        ("markup.heading.2".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("markup.heading.3".into(), Style::new(Color::new(58, 104, 74), None, false, false, false, false)),
        ("markup.heading.4".into(), Style::new(Color::new(61, 101, 104), None, false, false, false, false)),
        ("markup.link.url".into(), Style::new(Color::new(120, 146, 189), None, false, false, false, false)),
        ("markup.list".into(), Style::new(Color::new(204, 164, 120), None, false, false, false, false)),
        ("markup.quote".into(), Style::new(Color::new(125, 102, 88), None, false, false, true, false)),
        ("markup.raw".into(), Style::new(Color::new(125, 102, 88), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(84, 67, 58), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(84, 67, 58), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(144, 65, 128), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(144, 65, 128), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(191, 0, 33), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(84, 67, 58), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(204, 164, 120), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(199, 123, 139), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(70, 90, 164), None, false, false, true, false)),
        ("string.documentation".into(), Style::new(Color::new(70, 90, 164), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(120, 146, 189), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(70, 90, 164), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(61, 101, 104), None, false, false, false, false)),
        ("string.special.path".into(), Style::new(Color::new(120, 146, 189), None, false, false, false, false)),
        ("string.special.symbol".into(), Style::new(Color::new(84, 67, 58), None, false, false, true, false)),
        ("string.special.url".into(), Style::new(Color::new(120, 146, 189), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(61, 101, 104), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(204, 164, 120), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(115, 151, 151), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(188, 92, 0), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(84, 67, 58), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(84, 67, 58), None, false, false, true, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(160, 109, 0), None, false, false, false, false)),
    ]))
}
