//! The 'falcon' theme collection in this module was extracted from <https://github.com/fenetikm/falcon> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn falcon() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(180, 180, 185), Some(Color::new(2, 2, 33)), false, false, false, false)),
        ("annotation".into(), Style::new(Color::new(207, 193, 178), None, false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(207, 193, 178), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(180, 180, 185), None, false, false, true, false)),
        ("character".into(), Style::new(Color::new(200, 208, 227), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(120, 120, 130), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(158, 30, 0), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(120, 120, 130), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(2, 2, 33), Some(Color::new(207, 193, 178)), false, false, true, false)),
        ("comment.warning".into(), Style::new(Color::new(188, 143, 63), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(255, 197, 82), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(180, 180, 185), None, false, false, false, true)),
        ("constant.builtin".into(), Style::new(Color::new(180, 180, 185), None, false, false, true, false)),
        ("constant.macro".into(), Style::new(Color::new(207, 193, 178), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(180, 180, 185), None, false, false, false, true)),
        ("diff.delta".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(179, 246, 192), None, false, false, false, false)),
        ("error".into(), Style::new(Color::new(255, 197, 82), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(255, 197, 82), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(153, 164, 188), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(180, 180, 185), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(255, 197, 82), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(207, 193, 178), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(54, 54, 58), Some(Color::new(2, 2, 33)), false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(87, 87, 94), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(54, 54, 58), Some(Color::new(2, 2, 33)), false, false, false, false)),
        ("include".into(), Style::new(Color::new(207, 193, 178), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(255, 197, 82), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(207, 193, 178), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(153, 164, 188), None, false, false, false, false)),
        ("literal".into(), Style::new(Color::new(200, 208, 227), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(207, 193, 178), None, false, false, false, false)),
        ("markup.link".into(), Style::new(Color::new(153, 164, 188), None, true, false, false, false)),
        ("method".into(), Style::new(Color::new(180, 180, 185), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(223, 223, 229), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(207, 193, 178), None, false, false, false, false)),
        ("note".into(), Style::new(Color::new(2, 2, 33), Some(Color::new(207, 193, 178)), false, false, true, false)),
        ("number".into(), Style::new(Color::new(180, 180, 185), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(180, 180, 185), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(153, 164, 188), None, false, false, false, false)),
        ("parameter.reference".into(), Style::new(Color::new(153, 164, 188), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(153, 164, 188), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(223, 223, 229), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(223, 223, 229), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(223, 223, 229), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(223, 223, 229), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(153, 164, 188), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(200, 208, 227), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(200, 208, 227), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(200, 208, 227), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(200, 208, 227), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(153, 164, 188), None, true, false, false, false)),
        ("structure".into(), Style::new(Color::new(223, 223, 229), None, false, false, false, false)),
        ("symbol".into(), Style::new(Color::new(153, 164, 188), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(180, 180, 185), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(223, 223, 229), None, false, false, false, false)),
        ("title".into(), Style::new(Color::new(207, 193, 178), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(223, 223, 229), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(223, 223, 229), None, false, false, false, false)),
        ("uri".into(), Style::new(Color::new(153, 164, 188), None, true, false, false, false)),
        ("variable".into(), Style::new(Color::new(224, 226, 234), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(255, 118, 26), None, false, false, false, false)),
        ("warning".into(), Style::new(Color::new(188, 143, 63), None, false, false, false, false)),
    ]))
}
