//! The gruvbox themes in this module were extracted from <https://github.com/ellisonleao/gruvbox.nvim>
//!
//! The module source is automatically generated with `cargo xtask codegen` inside the
//! syntastica workspace.

use std::collections::BTreeMap;

use syntastica_core::{
    config::{Config, ThemeValue},
    theme,
};

pub fn dark() -> Config {
    let mut palette = theme! {
        "aqua": "#8ec07c",
        "bg0": "#282828",
        "bg1": "#3c3836",
        "bg2": "#504945",
        "bg3": "#665c54",
        "bg4": "#7c6f64",
        "blue": "#83a598",
        "fg0": "#fbf1c7",
        "fg1": "#ebdbb2",
        "fg2": "#d5c4a1",
        "fg3": "#bdae93",
        "fg4": "#a89984",
        "gray": "#928374",
        "green": "#b8bb26",
        "neutral_aqua": "#689d6a",
        "neutral_blue": "#458588",
        "neutral_green": "#98971a",
        "neutral_purple": "#b16286",
        "neutral_red": "#cc241d",
        "neutral_yellow": "#d79921",
        "orange": "#fe8019",
        "purple": "#d3869b",
        "red": "#fb4934",
        "yellow": "#fabd2f",
    }
    .into_inner();
    palette.append(&mut theme());
    palette.into()
}

pub fn light() -> Config {
    let mut palette = theme! {
        "aqua": "#427b58",
        "bg0": "#fbf1c7",
        "bg1": "#ebdbb2",
        "bg2": "#d5c4a1",
        "bg3": "#bdae93",
        "bg4": "#a89984",
        "blue": "#076678",
        "fg0": "#282828",
        "fg1": "#3c3836",
        "fg2": "#504945",
        "fg3": "#665c54",
        "fg4": "#7c6f64",
        "gray": "#928374",
        "green": "#79740e",
        "neutral_aqua": "#689d6a",
        "neutral_blue": "#458588",
        "neutral_green": "#98971a",
        "neutral_purple": "#b16286",
        "neutral_red": "#cc241d",
        "neutral_yellow": "#d79921",
        "orange": "#af3a03",
        "purple": "#8f3f71",
        "red": "#9d0006",
        "yellow": "#b57614",
    }
    .into_inner();
    palette.append(&mut theme());
    palette.into()
}

fn theme() -> BTreeMap<String, ThemeValue> {
    theme! {
        "attribute": "$aqua",
        "boolean": "$purple",
        "character": "$purple",
        "comment": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: true,
            bold: false,
            link: "gray",
        },
        "conditional": "$red",
        "constant": "$purple",
        "constant.builtin": "$orange",
        "constant.macro": "$aqua",
        "constructor": "$orange",
        "define": "$aqua",
        "exception": "$red",
        "field": "$blue",
        "float": "$purple",
        "function": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: true,
            link: "green",
        },
        "function.builtin": "$orange",
        "function.call": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: true,
            link: "green",
        },
        "function.macro": "$aqua",
        "include": "$aqua",
        "keyword": "$red",
        "keyword.function": "$red",
        "keyword.operator": "$red",
        "keyword.return": "$red",
        "label": "$red",
        "macro": "$aqua",
        "method": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: true,
            link: "green",
        },
        "method.call": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: true,
            link: "green",
        },
        "namespace": "$fg1",
        "number": "$purple",
        "operator": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: false,
            link: "orange",
        },
        "parameter": "$blue",
        "preproc": "$aqua",
        "property": "$blue",
        "repeat": "$red",
        "storageclass": "$orange",
        "string": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: true,
            bold: false,
            link: "green",
        },
        "string.regex": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: true,
            bold: false,
            link: "green",
        },
        "structure": "$aqua",
        "symbol": "$blue",
        "tag.attribute": "$blue",
        "text": "$fg1",
        "text.danger": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: true,
            link: "bg0",
        },
        "text.danger.comment": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: true,
            link: "fg0",
        },
        "text.diff.add": "$green",
        "text.diff.delete": "$red",
        "text.emphasis": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: true,
            bold: false,
            link: "fg1",
        },
        "text.environment": "$aqua",
        "text.environment.name": "$yellow",
        "text.literal": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: true,
            bold: false,
            link: "green",
        },
        "text.math": "$orange",
        "text.note.comment": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: true,
            link: "purple",
        },
        "text.reference": "$purple",
        "text.strike": {
            color: None,
            underline: false,
            strikethrough: true,
            italic: false,
            bold: false,
            link: "fg1",
        },
        "text.strong": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: true,
            link: "fg1",
        },
        "text.title": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: true,
            link: "green",
        },
        "text.todo": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: true,
            bold: true,
            link: "bg0",
        },
        "text.underline": {
            color: None,
            underline: true,
            strikethrough: false,
            italic: false,
            bold: false,
            link: "fg1",
        },
        "text.uri": {
            color: None,
            underline: true,
            strikethrough: false,
            italic: false,
            bold: false,
            link: "blue",
        },
        "text.warning": {
            color: None,
            underline: false,
            strikethrough: false,
            italic: false,
            bold: true,
            link: "red",
        },
        "type": "$yellow",
        "type.builtin": "$yellow",
        "type.definition": "$yellow",
        "type.qualifier": "$yellow",
        "variable": "$fg1",
        "variable.builtin": "$orange",
    }
    .into_inner()
}
