//! The 'gruvbox' theme collection in this module was extracted from <https://github.com/ellisonleao/gruvbox.nvim> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn dark() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(235, 219, 178), Some(Color::new(40, 40, 40)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(142, 192, 124), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(211, 134, 155), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(211, 134, 155), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(146, 131, 116), None, false, false, true, false)),
        ("conditional".into(), Style::new(Color::new(251, 73, 52), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(211, 134, 155), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(142, 192, 124), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("debug".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(142, 192, 124), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(251, 73, 52), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(131, 165, 152), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(211, 134, 155), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(184, 187, 38), None, false, false, false, true)),
        ("function.builtin".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("function.call".into(), Style::new(Color::new(184, 187, 38), None, false, false, false, true)),
        ("function.macro".into(), Style::new(Color::new(142, 192, 124), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(142, 192, 124), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(251, 73, 52), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(251, 73, 52), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(251, 73, 52), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(251, 73, 52), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(251, 73, 52), None, false, false, false, false)),
        ("macro".into(), Style::new(Color::new(142, 192, 124), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(184, 187, 38), None, false, false, false, true)),
        ("method.call".into(), Style::new(Color::new(184, 187, 38), None, false, false, false, true)),
        ("namespace".into(), Style::new(Color::new(235, 219, 178), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(211, 134, 155), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(131, 165, 152), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(142, 192, 124), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(131, 165, 152), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(251, 73, 52), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(184, 187, 38), None, false, false, true, false)),
        ("string.escape".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(184, 187, 38), None, false, false, true, false)),
        ("string.special".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("structure".into(), Style::new(Color::new(142, 192, 124), None, false, false, false, false)),
        ("symbol".into(), Style::new(Color::new(131, 165, 152), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(131, 165, 152), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(235, 219, 178), None, false, false, false, false)),
        ("text.danger".into(), Style::new(Color::new(40, 40, 40), Some(Color::new(251, 73, 52)), false, false, false, true)),
        ("text.danger.comment".into(), Style::new(Color::new(251, 241, 199), Some(Color::new(251, 73, 52)), false, false, false, true)),
        ("text.diff.add".into(), Style::new(Color::new(184, 187, 38), None, false, false, false, false)),
        ("text.diff.delete".into(), Style::new(Color::new(251, 73, 52), None, false, false, false, false)),
        ("text.environment".into(), Style::new(Color::new(142, 192, 124), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(250, 189, 47), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(184, 187, 38), None, false, false, true, false)),
        ("text.math".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("text.note".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
        ("text.note.comment".into(), Style::new(Color::new(211, 134, 155), None, false, false, false, true)),
        ("text.reference".into(), Style::new(Color::new(211, 134, 155), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(184, 187, 38), None, false, false, false, true)),
        ("text.todo".into(), Style::new(Color::new(40, 40, 40), Some(Color::new(250, 189, 47)), false, false, true, true)),
        ("text.uri".into(), Style::new(Color::new(131, 165, 152), None, true, false, false, false)),
        ("text.warning".into(), Style::new(Color::new(251, 73, 52), None, false, false, false, true)),
        ("type".into(), Style::new(Color::new(250, 189, 47), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(250, 189, 47), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(250, 189, 47), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(250, 189, 47), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(235, 219, 178), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(254, 128, 25), None, false, false, false, false)),
    ]))
}

#[rustfmt::skip]
pub fn light() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(60, 56, 54), Some(Color::new(251, 241, 199)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(66, 123, 88), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(143, 63, 113), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(143, 63, 113), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(146, 131, 116), None, false, false, true, false)),
        ("conditional".into(), Style::new(Color::new(157, 0, 6), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(143, 63, 113), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(66, 123, 88), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("debug".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(66, 123, 88), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(157, 0, 6), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(7, 102, 120), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(143, 63, 113), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(121, 116, 14), None, false, false, false, true)),
        ("function.builtin".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("function.call".into(), Style::new(Color::new(121, 116, 14), None, false, false, false, true)),
        ("function.macro".into(), Style::new(Color::new(66, 123, 88), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(66, 123, 88), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(157, 0, 6), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(157, 0, 6), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(157, 0, 6), None, false, false, false, false)),
        ("keyword.return".into(), Style::new(Color::new(157, 0, 6), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(157, 0, 6), None, false, false, false, false)),
        ("macro".into(), Style::new(Color::new(66, 123, 88), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(121, 116, 14), None, false, false, false, true)),
        ("method.call".into(), Style::new(Color::new(121, 116, 14), None, false, false, false, true)),
        ("namespace".into(), Style::new(Color::new(60, 56, 54), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(143, 63, 113), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(7, 102, 120), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(66, 123, 88), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(7, 102, 120), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(157, 0, 6), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(121, 116, 14), None, false, false, true, false)),
        ("string.escape".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(121, 116, 14), None, false, false, true, false)),
        ("string.special".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("structure".into(), Style::new(Color::new(66, 123, 88), None, false, false, false, false)),
        ("symbol".into(), Style::new(Color::new(7, 102, 120), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(7, 102, 120), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(60, 56, 54), None, false, false, false, false)),
        ("text.danger".into(), Style::new(Color::new(251, 241, 199), Some(Color::new(157, 0, 6)), false, false, false, true)),
        ("text.danger.comment".into(), Style::new(Color::new(40, 40, 40), Some(Color::new(157, 0, 6)), false, false, false, true)),
        ("text.diff.add".into(), Style::new(Color::new(121, 116, 14), None, false, false, false, false)),
        ("text.diff.delete".into(), Style::new(Color::new(157, 0, 6), None, false, false, false, false)),
        ("text.environment".into(), Style::new(Color::new(66, 123, 88), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(181, 118, 20), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(121, 116, 14), None, false, false, true, false)),
        ("text.math".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("text.note".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
        ("text.note.comment".into(), Style::new(Color::new(143, 63, 113), None, false, false, false, true)),
        ("text.reference".into(), Style::new(Color::new(143, 63, 113), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(121, 116, 14), None, false, false, false, true)),
        ("text.todo".into(), Style::new(Color::new(251, 241, 199), Some(Color::new(181, 118, 20)), false, false, true, true)),
        ("text.uri".into(), Style::new(Color::new(7, 102, 120), None, true, false, false, false)),
        ("text.warning".into(), Style::new(Color::new(157, 0, 6), None, false, false, false, true)),
        ("type".into(), Style::new(Color::new(181, 118, 20), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(181, 118, 20), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(181, 118, 20), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(181, 118, 20), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(60, 56, 54), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(175, 58, 3), None, false, false, false, false)),
    ]))
}
