//! The 'moonfly' theme collection in this module was extracted from <https://github.com/bluz71/vim-moonfly-colors> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn moonfly() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(198, 198, 198), Some(Color::new(8, 8, 8)), false, false, false, false)),
        ("annotation".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(116, 178, 255), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(174, 129, 255), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(148, 148, 148), None, false, false, true, false)),
        ("conditional".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(121, 218, 200), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(140, 200, 95), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(54, 198, 146), None, false, false, false, false)),
        ("danger".into(), Style::new(Color::new(227, 199, 138), Some(Color::new(38, 38, 38)), false, false, false, false)),
        ("debug".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("error".into(), Style::new(Color::new(255, 84, 84), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(121, 218, 200), None, false, false, false, false)),
        ("field.yaml".into(), Style::new(Color::new(128, 160, 255), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(222, 147, 95), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(116, 178, 255), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(116, 178, 255), None, false, false, false, false)),
        ("function.call".into(), Style::new(Color::new(116, 178, 255), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(116, 178, 255), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("keyword.gitcommit".into(), Style::new(Color::new(116, 178, 255), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(121, 218, 200), None, false, false, false, false)),
        ("macro".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(116, 178, 255), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(121, 218, 200), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(222, 147, 95), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(225, 150, 162), None, false, false, false, false)),
        ("parameter.bash".into(), Style::new(Color::new(121, 218, 200), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(121, 218, 200), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(198, 198, 198), None, false, false, false, false)),
        ("punctuation.delimiter.astro".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("punctuation.delimiter.css".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("punctuation.delimiter.rust".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("punctuation.delimiter.scss".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("punctuation.delimiter.yaml".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(240, 148, 121), None, false, false, false, false)),
        ("storageclass.rust".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(194, 194, 146), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(121, 218, 200), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("symbol".into(), Style::new(Color::new(174, 129, 255), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(128, 160, 255), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(121, 218, 200), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(133, 220, 133), None, false, false, false, false)),
        ("text.danger".into(), Style::new(Color::new(255, 84, 84), None, false, false, false, false)),
        ("text.diff.delete".into(), Style::new(Color::new(98, 98, 98), Some(Color::new(48, 48, 48)), false, false, false, false)),
        ("text.emphasis".into(), Style::new(Color::new(225, 150, 162), None, false, false, true, false)),
        ("text.environment".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(54, 198, 146), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(194, 194, 146), None, false, false, false, false)),
        ("text.math".into(), Style::new(Color::new(230, 94, 114), None, false, false, false, false)),
        ("text.note".into(), Style::new(Color::new(148, 148, 148), None, false, false, false, false)),
        ("text.reference".into(), Style::new(Color::new(140, 200, 95), None, false, false, false, false)),
        ("text.reference.gitcommit".into(), Style::new(Color::new(128, 160, 255), None, false, false, false, false)),
        ("text.strong".into(), Style::new(Color::new(225, 150, 162), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(128, 160, 255), None, false, false, false, false)),
        ("text.title.astro".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("text.title.gitcommit".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("text.title.help".into(), Style::new(Color::new(116, 178, 255), None, false, false, false, false)),
        ("text.title.html".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("text.title.svelte".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("text.title.vue".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(227, 199, 138), Some(Color::new(38, 38, 38)), false, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(174, 129, 255), None, false, false, false, false)),
        ("text.uri.astro".into(), Style::new(Color::new(207, 135, 232), None, false, false, true, false)),
        ("text.uri.gitcommit".into(), Style::new(Color::new(54, 198, 146), None, false, false, false, false)),
        ("text.uri.html".into(), Style::new(Color::new(207, 135, 232), None, false, false, true, false)),
        ("text.uri.svelte".into(), Style::new(Color::new(207, 135, 232), None, false, false, true, false)),
        ("text.uri.vue".into(), Style::new(Color::new(207, 135, 232), None, false, false, true, false)),
        ("text.warning".into(), Style::new(Color::new(227, 199, 138), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(54, 198, 146), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(54, 198, 146), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(54, 198, 146), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(207, 135, 232), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(198, 198, 198), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(133, 220, 133), None, false, false, false, false)),
        ("variable.builtin.vim".into(), Style::new(Color::new(54, 198, 146), None, false, false, false, false)),
        ("variable.scss".into(), Style::new(Color::new(121, 218, 200), None, false, false, false, false)),
        ("variable.vim".into(), Style::new(Color::new(121, 218, 200), None, false, false, false, false)),
    ]))
}
