//! The 'neon' theme collection in this module was extracted from <https://github.com/rafamadriz/neon> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn default() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(197, 205, 217), Some(Color::new(43, 45, 55)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("character".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(77, 181, 189), None, false, false, true, true)),
        ("comment.warning".into(), Style::new(Color::new(252, 224, 148), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(169, 161, 225), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("constructor".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("diff.delta".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(179, 246, 192), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(58, 62, 78), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(103, 110, 149), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(58, 62, 78), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("markup.heading".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("markup.link".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("module".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("number".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(236, 190, 123), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("string".into(), Style::new(Color::new(160, 201, 128), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("tag".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("type".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("variable".into(), Style::new(Color::new(224, 226, 234), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
    ]))
}

#[rustfmt::skip]
pub fn doom() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(187, 194, 207), Some(Color::new(40, 44, 52)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("character".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(77, 181, 189), None, false, false, true, true)),
        ("comment.warning".into(), Style::new(Color::new(252, 224, 148), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(169, 161, 225), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("constructor".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("diff.delta".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(179, 246, 192), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(63, 68, 74), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(103, 110, 149), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(63, 68, 74), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("markup.heading".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("markup.link".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("module".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("number".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(236, 190, 123), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("string".into(), Style::new(Color::new(160, 201, 128), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("tag".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("type".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("variable".into(), Style::new(Color::new(224, 226, 234), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
    ]))
}

#[rustfmt::skip]
pub fn dark() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(197, 205, 217), Some(Color::new(13, 17, 23)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("character".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(77, 181, 189), None, false, false, true, true)),
        ("comment.warning".into(), Style::new(Color::new(252, 224, 148), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(169, 161, 225), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("constructor".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("diff.delta".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(179, 246, 192), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(51, 54, 68), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(103, 110, 149), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(51, 54, 68), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("markup.heading".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("markup.link".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("module".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("number".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(236, 190, 123), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("string".into(), Style::new(Color::new(160, 201, 128), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("tag".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("type".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("variable".into(), Style::new(Color::new(224, 226, 234), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
    ]))
}

#[rustfmt::skip]
pub fn light() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(76, 86, 106), Some(Color::new(211, 211, 211)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("character".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(255, 102, 85), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(9, 151, 179), None, false, false, true, true)),
        ("comment.warning".into(), Style::new(Color::new(252, 224, 148), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(147, 112, 219), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("constructor".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("diff.delta".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(179, 246, 192), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(160, 161, 167), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(103, 110, 149), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(160, 161, 167), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(9, 151, 179), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("markup.heading".into(), Style::new(Color::new(9, 151, 179), None, false, false, false, false)),
        ("markup.link".into(), Style::new(Color::new(9, 151, 179), None, true, false, false, false)),
        ("module".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("number".into(), Style::new(Color::new(255, 102, 85), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(255, 102, 85), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(193, 132, 1), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("string".into(), Style::new(Color::new(80, 161, 79), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(9, 151, 179), None, true, false, false, false)),
        ("tag".into(), Style::new(Color::new(255, 102, 85), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("type".into(), Style::new(Color::new(9, 151, 179), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("variable".into(), Style::new(Color::new(224, 226, 234), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
    ]))
}
