//! The 'neon' theme collection in this module was extracted from <https://github.com/rafamadriz/neon> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn default() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(197, 205, 217), Some(Color::new(43, 45, 55)), false, false, false, false)),
        ("character".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("conditional".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(169, 161, 225), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("constant.macro".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("debug".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("function.macro".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("macro".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(236, 190, 123), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(160, 201, 128), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("text.reference".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(77, 181, 189), None, false, false, true, true)),
        ("text.underline".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("type".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
    ]))
}

#[rustfmt::skip]
pub fn doom() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(187, 194, 207), Some(Color::new(40, 44, 52)), false, false, false, false)),
        ("character".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("conditional".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(169, 161, 225), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("constant.macro".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("debug".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("function.macro".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("macro".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(236, 190, 123), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(160, 201, 128), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("text.reference".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(77, 181, 189), None, false, false, true, true)),
        ("text.underline".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("type".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
    ]))
}

#[rustfmt::skip]
pub fn dark() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(197, 205, 217), Some(Color::new(13, 17, 23)), false, false, false, false)),
        ("character".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("conditional".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(169, 161, 225), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("constant.macro".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("debug".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(108, 182, 235), None, false, false, true, false)),
        ("function.macro".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("macro".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(236, 190, 123), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(160, 201, 128), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(236, 114, 121), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("text.reference".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(77, 181, 189), None, false, false, true, true)),
        ("text.underline".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(77, 181, 189), None, true, false, false, false)),
        ("type".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(77, 181, 189), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(108, 182, 235), None, false, false, false, false)),
    ]))
}

#[rustfmt::skip]
pub fn light() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(76, 86, 106), Some(Color::new(211, 211, 211)), false, false, false, false)),
        ("character".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("conditional".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(147, 112, 219), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("constant.macro".into(), Style::new(Color::new(9, 151, 179), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("debug".into(), Style::new(Color::new(255, 102, 85), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(9, 151, 179), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(255, 102, 85), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(34, 87, 160), None, false, false, true, false)),
        ("function.macro".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(9, 151, 179), None, false, false, false, false)),
        ("macro".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(255, 102, 85), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(193, 132, 1), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(9, 151, 179), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(80, 161, 79), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(218, 133, 72), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(255, 102, 85), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(126, 130, 148), None, false, false, true, false)),
        ("text.reference".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(9, 151, 179), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(9, 151, 179), None, false, false, true, true)),
        ("text.underline".into(), Style::new(Color::new(9, 151, 179), None, true, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(9, 151, 179), None, true, false, false, false)),
        ("type".into(), Style::new(Color::new(9, 151, 179), None, false, false, false, false)),
        ("type.definition".into(), Style::new(Color::new(9, 151, 179), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(34, 87, 160), None, false, false, false, false)),
    ]))
}
