//! The 'nightfly' theme collection in this module was extracted from <https://github.com/bluz71/vim-nightfly-colors> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn nightfly() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(195, 204, 220), Some(Color::new(1, 22, 39)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("attribute.bind.html".into(), Style::new(Color::new(135, 188, 255), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("attribute.directive.value.html".into(), Style::new(Color::new(176, 178, 244), None, false, false, false, false)),
        ("attribute.on.html".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("attribute.zig".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(174, 129, 255), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("character.special.vim".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(124, 143, 143), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(252, 81, 78), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(124, 143, 143), None, false, false, false, false)),
        ("comment.ok".into(), Style::new(Color::new(161, 205, 94), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(227, 209, 138), Some(Color::new(14, 41, 63)), false, false, false, false)),
        ("comment.warning".into(), Style::new(Color::new(227, 209, 138), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(161, 205, 94), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("define".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(75, 100, 121), Some(Color::new(44, 48, 67)), false, false, false, false)),
        ("error".into(), Style::new(Color::new(252, 81, 78), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(176, 178, 244), None, false, false, false, false)),
        ("field.yaml".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("function.call".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("function.macro.vim".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("function.method".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("function.method.call".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(14, 41, 63), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(14, 41, 63), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("include.rust".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("keyword.conditional".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("keyword.directive".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("keyword.directive.define".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("keyword.exception".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("keyword.gitcommit".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("keyword.import".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("keyword.import.bash".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("keyword.import.rust".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("keyword.repeat".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("keyword.storage".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("keyword.storage.rust".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("markup.environment".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("markup.environment.name".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("markup.heading.1.markdown".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("markup.heading.1.vimdoc".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("markup.heading.2.markdown".into(), Style::new(Color::new(176, 178, 244), None, false, false, false, false)),
        ("markup.heading.2.vimdoc".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("markup.heading.3.markdown".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("markup.heading.4.markdown".into(), Style::new(Color::new(247, 140, 108), None, false, false, false, false)),
        ("markup.heading.5.markdown".into(), Style::new(Color::new(135, 188, 255), None, false, false, false, false)),
        ("markup.heading.6.markdown".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("markup.heading.help".into(), Style::new(Color::new(135, 188, 255), None, false, false, false, false)),
        ("markup.heading.markdown".into(), Style::new(Color::new(135, 188, 255), None, false, false, false, false)),
        ("markup.italic".into(), Style::new(Color::new(227, 154, 166), None, false, false, true, false)),
        ("markup.link".into(), Style::new(Color::new(161, 205, 94), None, false, false, false, false)),
        ("markup.link.gitcommit".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("markup.link.label".into(), Style::new(Color::new(161, 205, 94), None, false, false, false, false)),
        ("markup.link.url".into(), Style::new(Color::new(174, 129, 255), None, true, false, false, false)),
        ("markup.link.url.astro".into(), Style::new(Color::new(199, 146, 234), None, false, false, true, false)),
        ("markup.link.url.gitcommit".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("markup.link.url.html".into(), Style::new(Color::new(199, 146, 234), None, false, false, true, false)),
        ("markup.link.url.svelte".into(), Style::new(Color::new(199, 146, 234), None, false, false, true, false)),
        ("markup.link.url.vue".into(), Style::new(Color::new(199, 146, 234), None, false, false, true, false)),
        ("markup.list".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("markup.list.checked".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("markup.list.latex".into(), Style::new(Color::new(174, 129, 255), None, false, false, false, false)),
        ("markup.list.unchecked".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("markup.math".into(), Style::new(Color::new(135, 188, 255), None, false, false, false, false)),
        ("markup.quote".into(), Style::new(Color::new(124, 143, 143), None, false, false, false, false)),
        ("markup.raw".into(), Style::new(Color::new(236, 196, 141), None, false, false, false, false)),
        ("markup.raw.vimdoc".into(), Style::new(Color::new(227, 154, 166), None, false, false, false, false)),
        ("markup.strong".into(), Style::new(Color::new(227, 154, 166), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(161, 205, 94), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("namespace.builtin".into(), Style::new(Color::new(161, 205, 94), None, false, false, false, false)),
        ("namespace.latex".into(), Style::new(Color::new(176, 178, 244), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(247, 140, 108), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(247, 140, 108), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(227, 154, 166), None, false, false, false, false)),
        ("parameter.bash".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("parameter.builtin".into(), Style::new(Color::new(227, 154, 166), None, false, false, false, false)),
        ("preproc".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(176, 178, 244), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(195, 204, 220), None, false, false, false, false)),
        ("punctuation.delimiter.astro".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("punctuation.delimiter.css".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("punctuation.delimiter.rust".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("punctuation.delimiter.scss".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("punctuation.delimiter.yaml".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("storageclass".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("storageclass.rust".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(236, 196, 141), None, false, false, false, false)),
        ("string.documentation".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("string.json".into(), Style::new(Color::new(133, 220, 133), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("string.special.path".into(), Style::new(Color::new(227, 154, 166), None, false, false, false, false)),
        ("string.special.symbol".into(), Style::new(Color::new(174, 129, 255), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(174, 129, 255), None, false, false, false, false)),
        ("symbol".into(), Style::new(Color::new(174, 129, 255), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(161, 205, 94), None, false, false, false, false)),
        ("tag.javascript".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("tag.jsx".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("tag.tsx".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("tag.typescript".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("text.danger".into(), Style::new(Color::new(252, 81, 78), None, false, false, false, false)),
        ("text.diff.delete".into(), Style::new(Color::new(75, 100, 121), Some(Color::new(44, 48, 67)), false, false, false, false)),
        ("text.emphasis".into(), Style::new(Color::new(227, 154, 166), None, false, false, true, false)),
        ("text.environment".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("text.environment.name".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("text.literal".into(), Style::new(Color::new(236, 196, 141), None, false, false, false, false)),
        ("text.literal.vimdoc".into(), Style::new(Color::new(227, 154, 166), None, false, false, false, false)),
        ("text.math".into(), Style::new(Color::new(135, 188, 255), None, false, false, false, false)),
        ("text.note".into(), Style::new(Color::new(124, 143, 143), None, false, false, false, false)),
        ("text.reference".into(), Style::new(Color::new(161, 205, 94), None, false, false, false, false)),
        ("text.reference.gitcommit".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("text.reference.markdown_inline".into(), Style::new(Color::new(161, 205, 94), None, false, false, false, false)),
        ("text.strong".into(), Style::new(Color::new(227, 154, 166), None, false, false, false, false)),
        ("text.title".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("text.title.1.markdown".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("text.title.1.marker.markdown".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("text.title.1.vimdoc".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("text.title.2.markdown".into(), Style::new(Color::new(176, 178, 244), None, false, false, false, false)),
        ("text.title.2.marker.markdown".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("text.title.2.vimdoc".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("text.title.3.markdown".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("text.title.3.marker.markdown".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("text.title.4.markdown".into(), Style::new(Color::new(247, 140, 108), None, false, false, false, false)),
        ("text.title.4.marker.markdown".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("text.title.5.markdown".into(), Style::new(Color::new(135, 188, 255), None, false, false, false, false)),
        ("text.title.5.marker.markdown".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("text.title.6.markdown".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("text.title.6.marker.markdown".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("text.title.help".into(), Style::new(Color::new(135, 188, 255), None, false, false, false, false)),
        ("text.title.markdown".into(), Style::new(Color::new(135, 188, 255), None, false, false, false, false)),
        ("text.todo".into(), Style::new(Color::new(227, 209, 138), Some(Color::new(14, 41, 63)), false, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(174, 129, 255), None, true, false, false, false)),
        ("text.uri.astro".into(), Style::new(Color::new(199, 146, 234), None, false, false, true, false)),
        ("text.uri.gitcommit".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("text.uri.html".into(), Style::new(Color::new(199, 146, 234), None, false, false, true, false)),
        ("text.uri.svelte".into(), Style::new(Color::new(199, 146, 234), None, false, false, true, false)),
        ("text.uri.vue".into(), Style::new(Color::new(199, 146, 234), None, false, false, true, false)),
        ("text.warning".into(), Style::new(Color::new(227, 209, 138), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("type.qualifier".into(), Style::new(Color::new(199, 146, 234), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(195, 204, 220), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(161, 205, 94), None, false, false, false, false)),
        ("variable.builtin.vim".into(), Style::new(Color::new(33, 199, 168), None, false, false, false, false)),
        ("variable.member".into(), Style::new(Color::new(176, 178, 244), None, false, false, false, false)),
        ("variable.member.ruby".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("variable.member.yaml".into(), Style::new(Color::new(130, 170, 255), None, false, false, false, false)),
        ("variable.parameter".into(), Style::new(Color::new(227, 154, 166), None, false, false, false, false)),
        ("variable.parameter.bash".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(255, 88, 116), None, false, false, false, false)),
        ("variable.scss".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
        ("variable.vim".into(), Style::new(Color::new(127, 219, 202), None, false, false, false, false)),
    ]))
}
