//! The 'oceanicnext' theme collection in this module was extracted from <https://github.com/mhartington/oceanic-next> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn dark() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(216, 222, 233), Some(Color::new(27, 43, 52)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(236, 95, 103), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(249, 145, 87), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(236, 95, 103), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(171, 121, 103), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(101, 115, 126), None, false, false, false, false)),
        ("comment.error".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(250, 200, 99), Some(Color::new(52, 61, 70)), false, false, false, true)),
        ("comment.warning".into(), Style::new(Color::new(252, 224, 148), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(197, 148, 197), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(249, 145, 87), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(216, 222, 233), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(179, 246, 192), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(236, 95, 103), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(102, 153, 204), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(101, 115, 126), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(101, 115, 126), Some(Color::new(27, 43, 52)), false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(101, 115, 126), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(197, 148, 197), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(197, 148, 197), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(197, 148, 197), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(102, 153, 204), None, false, false, false, true)),
        ("markup.link".into(), Style::new(Color::new(236, 95, 103), None, true, false, false, false)),
        ("method".into(), Style::new(Color::new(102, 153, 204), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(197, 148, 197), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(216, 222, 233), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(249, 145, 87), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(249, 145, 87), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(249, 145, 87), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(250, 200, 99), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(216, 222, 233), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(171, 121, 103), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(153, 199, 148), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(171, 121, 103), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(171, 121, 103), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(171, 121, 103), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(236, 95, 103), None, true, false, false, false)),
        ("symbol".into(), Style::new(Color::new(153, 199, 148), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(216, 222, 233), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(250, 200, 99), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(205, 211, 222), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(236, 95, 103), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(98, 179, 178), None, false, false, false, false)),
    ]))
}

#[rustfmt::skip]
pub fn light() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(27, 43, 52), Some(Color::new(245, 247, 250)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(208, 84, 91), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(219, 128, 77), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(208, 84, 91), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(150, 106, 91), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(167, 173, 186), None, false, false, false, false)),
        ("comment.error".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(220, 176, 87), Some(Color::new(212, 216, 220)), false, false, false, true)),
        ("comment.warning".into(), Style::new(Color::new(252, 224, 148), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(173, 130, 173), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(219, 128, 77), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(27, 43, 52), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(179, 246, 192), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(208, 84, 91), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(90, 135, 180), None, false, false, false, false)),
        ("function.builtin".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(167, 173, 186), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(167, 173, 186), Some(Color::new(245, 247, 250)), false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(167, 173, 186), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(173, 130, 173), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(173, 130, 173), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(173, 130, 173), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(90, 135, 180), None, false, false, false, true)),
        ("markup.link".into(), Style::new(Color::new(208, 84, 91), None, true, false, false, false)),
        ("method".into(), Style::new(Color::new(90, 135, 180), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(173, 130, 173), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(27, 43, 52), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(219, 128, 77), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(219, 128, 77), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(219, 128, 77), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(220, 176, 87), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(27, 43, 52), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(150, 106, 91), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(135, 175, 130), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(150, 106, 91), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(150, 106, 91), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(150, 106, 91), None, false, false, false, false)),
        ("string.special.url".into(), Style::new(Color::new(208, 84, 91), None, true, false, false, false)),
        ("symbol".into(), Style::new(Color::new(135, 175, 130), None, false, false, false, false)),
        ("tag".into(), Style::new(Color::new(27, 43, 52), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("type".into(), Style::new(Color::new(220, 176, 87), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(52, 61, 70), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(208, 84, 91), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(86, 158, 157), None, false, false, false, false)),
    ]))
}
