//! The 'oxocarbon' theme collection in this module was extracted from <https://github.com/nyoom-engineering/oxocarbon.nvim> using `auto_extract.py`.

use std::collections::BTreeMap;

use syntastica_core::{
    style::{Color, Style},
    theme::ResolvedTheme,
};

#[rustfmt::skip]
pub fn dark() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(208, 208, 208), Some(Color::new(22, 22, 22)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(130, 207, 255), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(190, 149, 255), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(82, 82, 82), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(66, 190, 101), None, false, false, false, false)),
        ("comment.warning".into(), Style::new(Color::new(190, 149, 255), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(190, 149, 255), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(140, 248, 247), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(255, 192, 185), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(179, 246, 192), None, false, false, false, false)),
        ("error".into(), Style::new(Color::new(51, 177, 255), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(130, 207, 255), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(130, 207, 255), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(255, 126, 182), None, false, false, false, true)),
        ("function.builtin".into(), Style::new(Color::new(255, 126, 182), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(57, 57, 57), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(82, 82, 82), Some(Color::new(22, 22, 22)), false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(57, 57, 57), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(61, 219, 217), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(61, 219, 217), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(130, 207, 255), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(130, 207, 255), None, false, false, false, false)),
        ("number.date".into(), Style::new(Color::new(61, 219, 217), None, false, false, false, false)),
        ("number.date.effective".into(), Style::new(Color::new(66, 190, 101), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(130, 207, 255), None, false, false, false, false)),
        ("number.interval".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("number.quantity".into(), Style::new(Color::new(51, 177, 255), None, false, false, false, false)),
        ("number.quantity.negative".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("number.status".into(), Style::new(Color::new(255, 126, 182), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(224, 226, 234), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(61, 219, 217), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(61, 219, 217), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(61, 219, 217), None, false, false, false, false)),
        ("reference".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(190, 149, 255), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(130, 207, 255), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("symbol".into(), Style::new(Color::new(130, 207, 255), None, false, false, false, true)),
        ("tag".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(130, 207, 255), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(130, 207, 255), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("text.emphasis".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, true)),
        ("text.literal".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("text.literal.commodity".into(), Style::new(Color::new(66, 190, 101), None, false, false, false, false)),
        ("text.strike".into(), Style::new(Color::new(238, 83, 150), None, false, true, false, false)),
        ("text.title".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("text.underline".into(), Style::new(Color::new(238, 83, 150), None, true, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(190, 149, 255), None, true, false, false, false)),
        ("type".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(120, 169, 255), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
    ]))
}

#[rustfmt::skip]
pub fn light() -> ResolvedTheme {
    ResolvedTheme::new(BTreeMap::from([
        ("_normal".into(), Style::new(Color::new(55, 71, 79), Some(Color::new(255, 255, 255)), false, false, false, false)),
        ("attribute".into(), Style::new(Color::new(255, 171, 145), None, false, false, false, false)),
        ("attribute.builtin".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("boolean".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("character".into(), Style::new(Color::new(190, 149, 255), None, false, false, false, false)),
        ("character.special".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("comment".into(), Style::new(Color::new(22, 22, 22), None, false, false, true, false)),
        ("comment.error".into(), Style::new(Color::new(255, 111, 0), None, false, false, false, false)),
        ("comment.note".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("comment.todo".into(), Style::new(Color::new(66, 190, 101), None, false, false, false, false)),
        ("comment.warning".into(), Style::new(Color::new(190, 149, 255), None, false, false, false, false)),
        ("conditional".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("constant".into(), Style::new(Color::new(190, 149, 255), None, false, false, false, false)),
        ("constant.builtin".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("constant.macro".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("constructor".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("diff.delta".into(), Style::new(Color::new(0, 115, 115), None, false, false, false, false)),
        ("diff.minus".into(), Style::new(Color::new(89, 0, 8), None, false, false, false, false)),
        ("diff.plus".into(), Style::new(Color::new(0, 85, 35), None, false, false, false, false)),
        ("error".into(), Style::new(Color::new(15, 98, 254), None, false, false, false, false)),
        ("exception".into(), Style::new(Color::new(255, 171, 145), None, false, false, false, false)),
        ("field".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("float".into(), Style::new(Color::new(255, 171, 145), None, false, false, false, false)),
        ("function".into(), Style::new(Color::new(103, 58, 183), None, false, false, false, true)),
        ("function.builtin".into(), Style::new(Color::new(103, 58, 183), None, false, false, false, false)),
        ("function.macro".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("ibl.indent.char.1".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("ibl.scope.char.1".into(), Style::new(Color::new(22, 22, 22), Some(Color::new(255, 255, 255)), false, false, false, false)),
        ("ibl.whitespace.char.1".into(), Style::new(Color::new(208, 208, 208), None, false, false, false, false)),
        ("include".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("keyword".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("keyword.function".into(), Style::new(Color::new(255, 126, 182), None, false, false, false, false)),
        ("keyword.operator".into(), Style::new(Color::new(255, 126, 182), None, false, false, false, false)),
        ("label".into(), Style::new(Color::new(255, 171, 145), None, false, false, false, false)),
        ("markup".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("markup.heading".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("method".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("module".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("module.builtin".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("namespace".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("number".into(), Style::new(Color::new(255, 171, 145), None, false, false, false, false)),
        ("number.date".into(), Style::new(Color::new(255, 126, 182), None, false, false, false, false)),
        ("number.date.effective".into(), Style::new(Color::new(66, 190, 101), None, false, false, false, false)),
        ("number.float".into(), Style::new(Color::new(255, 171, 145), None, false, false, false, false)),
        ("number.interval".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("number.quantity".into(), Style::new(Color::new(15, 98, 254), None, false, false, false, false)),
        ("number.quantity.negative".into(), Style::new(Color::new(255, 111, 0), None, false, false, false, false)),
        ("number.status".into(), Style::new(Color::new(103, 58, 183), None, false, false, false, false)),
        ("operator".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("parameter".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("property".into(), Style::new(Color::new(255, 111, 0), None, false, false, false, false)),
        ("punctuation".into(), Style::new(Color::new(20, 22, 27), None, false, false, false, false)),
        ("punctuation.bracket".into(), Style::new(Color::new(255, 126, 182), None, false, false, false, false)),
        ("punctuation.delimiter".into(), Style::new(Color::new(255, 126, 182), None, false, false, false, false)),
        ("punctuation.special".into(), Style::new(Color::new(255, 126, 182), None, false, false, false, false)),
        ("reference".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("repeat".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("string".into(), Style::new(Color::new(190, 149, 255), None, false, false, false, false)),
        ("string.escape".into(), Style::new(Color::new(255, 171, 145), None, false, false, false, false)),
        ("string.regex".into(), Style::new(Color::new(8, 189, 186), None, false, false, false, false)),
        ("string.regexp".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("string.special".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("symbol".into(), Style::new(Color::new(255, 171, 145), None, false, false, false, true)),
        ("tag".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("tag.attribute".into(), Style::new(Color::new(255, 171, 145), None, false, false, false, false)),
        ("tag.builtin".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("tag.delimiter".into(), Style::new(Color::new(255, 171, 145), None, false, false, false, false)),
        ("text".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("text.emphasis".into(), Style::new(Color::new(255, 111, 0), None, false, false, false, true)),
        ("text.literal".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("text.literal.commodity".into(), Style::new(Color::new(66, 190, 101), None, false, false, false, false)),
        ("text.strike".into(), Style::new(Color::new(255, 111, 0), None, false, true, false, false)),
        ("text.title".into(), Style::new(Color::new(255, 111, 0), None, false, false, false, false)),
        ("text.underline".into(), Style::new(Color::new(255, 111, 0), None, true, false, false, false)),
        ("text.uri".into(), Style::new(Color::new(190, 149, 255), None, true, false, false, false)),
        ("type".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("type.builtin".into(), Style::new(Color::new(238, 83, 150), None, false, false, false, false)),
        ("variable".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("variable.builtin".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
        ("variable.parameter.builtin".into(), Style::new(Color::new(55, 71, 79), None, false, false, false, false)),
    ]))
}
