#!/bin/bash

file="./syntastica-parsers-gitdep/Cargo.toml"
raw="$(cat "$file")"
header="
###########################################
### All following code is autogenerated ###
### by running \`cargo xtask codegen\` in ###
### the syntastica workspace. #############
###########################################
"
echo -n "${raw//"$header"*/"$header"}" > "$file"
