use std::fs;

use anyhow::Result;

const HEADER: &str = "
###########################################
### All following code is autogenerated ###
### by running `cargo xtask codegen` in ###
### the syntastica workspace. #############
###########################################
";

pub fn write() -> Result<()> {
    let toml_path = crate::WORKSPACE_DIR.join("syntastica-parsers-gitdep/Cargo.toml");
    let mut toml = fs::read_to_string(&toml_path)?;

    if let Some((preserve, _)) = toml.split_once(HEADER) {
        toml.truncate(preserve.len());
    }
    toml += HEADER;

    toml += r##"
[features]
#! ### Features
default = []

#! At least one of
#! <span class="stab portability"><code>some</code></span>,
#! <span class="stab portability"><code>most</code></span>, and
#! <span class="stab portability"><code>all</code></span>
#! must be enabled.

## Include parsers for the most widely known supported languages.
"##;
    syntastica_macros::parsers_gitdep_toml_feature_some!();
    toml += r##"
## Implies <span class="stab portability"><code>some</code></span>.
## Include parsers for most common languages.
"##;
    syntastica_macros::parsers_gitdep_toml_feature_most!();
    toml += r##"
## Implies <span class="stab portability"><code>most</code></span>.
## Include parsers for all supported languages.
"##;
    syntastica_macros::parsers_gitdep_toml_feature_all!();

    toml += r##"
## Meant to be enabled when building docs
docs = ["dep:document-features", "dep:rustc_version"]
"##;

    syntastica_macros::parsers_gitdep_toml_deps!();

    fs::write(&toml_path, toml)?;

    Ok(())
}
